### ISSUE TITLE
Dismiss fullscreen controller by vertical swipe

### ISSUE THREAD

**Issue by zvonicek** [zvonicek/ImageSlideshow#1]

**Comment by htarwara6245** [comment]
Yeah,If you add this,It will be awesome more !!!!Keep it up m8

**Comment by EduardJS** [comment]
Agreed, I was going to open an issue regarding exactly this one, was trying to find out if its possible ! Should add one like this buddy.

**Comment by kafejo** [comment]
see #27

**Comment by EduardJS** [comment]
@kafejo Oh, that's amazing ! If there could be added a tapToDismiss , It'd be perfect. Thank you for the pull request ! It's what we all needed !

**Comment by zvonicek** [comment]
@EduardJS `tapToDismiss` is different functionality than this. I've just created a new issue #29 for it so we can discuss it separately.
