### ISSUE TITLE
ImageSlideshow contains unsupported architectures

### ISSUE THREAD

**Issue by chardido** [zvonicek/ImageSlideshow#100]
When I submit project to Itunes Connect, it give me this error: 

> Frameworks/ImageSlideshow.framework contains unsupported architectures '[x86_64, i386]'

It's the only framework that give me error. What should I do?

**Comment by zvonicek** [comment]
Hi, how did you install ImageSlideshow? Via CocoaPods, Charthage or manually?

**Comment by zvonicek** [comment]
Check out this StackOverflow issue: http://stackoverflow.com/questions/30547283/submit-to-app-store-issues
In case you use Carthage make sure you have added a Build Phase `copy-frameworks` to your target.
