### ISSUE TITLE
Update Alamofire to 4.x

### ISSUE THREAD

**Issue by maxhis** [zvonicek/ImageSlideshow#101]
I'm using the latest version(4.x) of Alamofire - it conflict with the version(3.x) `ImageSlideshow/Alamofire` used. Appreciate if you can update the Alamofire to latest version, thanks.

**Comment by zvonicek** [comment]
Hi, are you using the `~> 1.0.0-beta.1` version? Latest Alamofire version (4.2.0) should work correctly on it.
