### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by kashif-izhar** [zvonicek/ImageSlideshow#103]
Can you please advise how to install it manually. I cannot use pod.

**Comment by LukA888** [comment]
Yes please!

**Comment by zvonicek** [comment]
There are several ways. The easiest one is to download a builded framework (ImageSlideshow.framework.zip) from [releases page](https://github.com/zvonicek/ImageSlideshow/releases/) and link it with your project (under`Linked Frameworks and Libraries` in your target). This framework does not include InputSources for external providers so you need to download the one you need from `ImageSlideshow/Classes/InputSources` and add it to your project.

You can also grab the whole `ImageSlideshow` directory and copy it to your project, but this can make future updates more difficult.
