### ISSUE TITLE
scaleAspectFill does not work the second time I present a cell.

### ISSUE THREAD

**Issue by aravasio** [zvonicek/ImageSlideshow#106]
Given I present a tableview with a cell that has an ImageSlideshow outlet in it, and that I then navigate back, then I present that tableview again, for some reason contentScaleMode is not working and I think is resetting to .center.
This is consistent with all contentScaleMode I've tried.

I'm not very sure how to explain it, but here it is in images:

First ok:
<img width="369" alt="1" src="https://cloud.githubusercontent.com/assets/7585675/21413645/a1a032e0-c7d7-11e6-999f-1e434200eefe.png">
<img width="338" alt="2" src="https://cloud.githubusercontent.com/assets/7585675/21413646/a1d13f98-c7d7-11e6-9b08-7527f2c2a84f.png">

Then nope:
<img width="360" alt="3" src="https://cloud.githubusercontent.com/assets/7585675/21413648/a1d27f98-c7d7-11e6-914d-089639601842.png">
<img width="345" alt="4" src="https://cloud.githubusercontent.com/assets/7585675/21413647/a1d25b08-c7d7-11e6-8a4e-2e144e273af6.png">

I checked in my codebase and that view is the only case where I'm setting the scaleMode, and it is as such:

         override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {

                 let cell = tableView.dequeueReusableCell(withIdentifier: "ArticleCell", for: indexPath) as! ArticleCell
                  cell.imageSlider.contentScaleMode = .scaleAspectFill
                  cell.imageSlider.slideshowInterval = 5
                  cell.imageSlider.zoomEnabled = true
                  cell.imageSlider.pageControlPosition = .insideScrollView
                  let gestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(self.didTapImageSlider))
                  cell.imageSlider.addGestureRecognizer(gestureRecognizer)
                  cell.categoryLabel.text = news?.categoryTitle
                  cell.titleLabel.text = news?.title
                  cell.dateLabel.text = news?.date
                  cell.leadLabel.text = news?.lead
                  cell.bodyLabel.text = news?.body
                  var sources = [InputSource]()
                  if let urls = news?.imagesUrls {
                           for url in urls {
                                    sources.append(AlamofireSource(urlString: url)!)
                        }
                }
                cell.imageSlider.setImageInputs(sources)
               return cell
        }

Any ideas, theory about what might be causing this? I'm actually really intrigued.

**Comment by zvonicek** [comment]
Hi, could you send me a project demonstrating this issue? I could have a look on that.

**Comment by aravasio** [comment]
Hey! Sorry I couldn't come back to you sooner.

I cannot provide you any more code than that due to legal reasons, but what I can do is tell you what I did to fix it.

Basically in ImageSlideshowItem.swift I made the following changes in line 151:

`fileprivate func calculatePictureSize() -> CGSize {
        if let image = imageView.image {
            let picSize = image.size
            let picRatio = picSize.width / picSize.height
            let screenRatio = screenSize().width / screenSize().height
            
            if (picRatio > screenRatio){
// REPLACED THIS
//                return CGSize(width: screenSize().width, height: screenSize().width / picSize.width * picSize.height)
//WITH THIS, which is the same one than the last else.
                return CGSize(width: screenSize().width, height: screenSize().height)
            } else {
                return CGSize(width: screenSize().height / picSize.height * picSize.width, height: screenSize().height)
            }
        } else {
            return CGSize(width: screenSize().width, height: screenSize().height)
        }
    }`
