### ISSUE TITLE
Fail in Xcode 8 swift2.3

### ISSUE THREAD

**Issue by vincendadiaz** [zvonicek/ImageSlideshow#107]
Hi there

The error log is : Unknown class _TtC14ImageSlideshow14ImageSlideshow in Interface Builder file

Whats wrong with it ?

Thanks

**Comment by zvonicek** [comment]
I'm not sure what the cause of this error could be, seems there's an issue with the framework linking in your project.

Also make sure you're using swift-2.3 branch.

**Comment by abeemukthees** [comment]
Uncheck - Inherit Module From Target
Set class & module as : ImageSlideshow
