### ISSUE TITLE
Does not find "ImageSlideshow" Module in Custom Class of Interface Builder?

### ISSUE THREAD

**Issue by seenoevo** [zvonicek/ImageSlideshow#108]
Hello, I'm doing a manual installation of ImageSlideshow instead of via cocoa pods. I added the framework from the .zip file as well as dragged over the "ImageSlideshow_framework" folder with all contents to my project.

I am able to perform `import ImageSlideshow` and Xcode finds out. I added a `UIView` in my storyboard, and in "Custom Class", Interface Builder is able to find "ImageSlideshow" for the **Class**, but it cannot find "ImageSlideshow" for **Module**.

I created a Test project and installed via cocoa pods and Interface Builder can find "ImageSlideshow" for **Module**, but won't find it for my manual installation.

I don't want to use cocoa pods. Does anyone know the issue?

**Comment by cmoijulien** [comment]
I have the same behavior :-(

**Comment by zvonicek** [comment]
I confirm this. After short googling this seems to be a known Xcode issue (see https://github.com/Carthage/Carthage/issues/763).

A positive news is that there's only problem with module autocompletion, so if you in the Interface Builder enter the class name "ImageSlideshow" first and then enter module name "ImageSlideshow", it should work correctly.
