### ISSUE TITLE
how to use this library with Xcode 8 and swift 3 ?

### ISSUE THREAD

**Issue by Mohammed-Eliass** [zvonicek/ImageSlideshow#111]
Hey there, after install it by pod what should I do to use it i my project ?
how to make it works with my views ?
Could you explain more , please  ?!

Add ImageSlideshow view to your view hierarchy either in Interface Builder or in code.
I meant this line

**Comment by shawn-shen** [comment]
Please check out the swift example for detailed usage.

**Comment by Mohammed-Eliass** [comment]
thanks
