### ISSUE TITLE
Custom animation

### ISSUE THREAD

**Issue by korgx9** [zvonicek/ImageSlideshow#113]
Hi 
Help needed. In my project I have rounded slideshow.
When I tap on slideshow it is zoom in, the animation looks good, but when I zoom out the corners of slideshow are staying angled when my slide show is rounded. Looks nasty.
Is it possible to customize the animation?

here [link](https://s27.postimg.org/tucy0qn83/profile_Rounded_Corners.gif)

thanks

**Comment by zvonicek** [comment]
Hi, this requires changes in ZoomAnimatedTransitioningDelegate which are bit beyond the scope now. I recommend you to subclass ZoomAnimatedTransitioningDelegate and customize the animation there.
