### ISSUE TITLE
[V1.0.0] Image doesn't display when scrolling back (left) from first image with preload function

### ISSUE THREAD

**Issue by shawn-shen** [zvonicek/ImageSlideshow#115]
This issue happens on sample project as well.

Steps to reproduce:
1. Open sample project.
2. In viewDidLoad, add slideshow.preload = ImagePreload.fixed(offset: 1);
3. Run project and swipe image left as soon as the project loads.
4. The image doesn't display or blinks then hide.

**Comment by dogo** [comment]
Yep, same here

**Comment by zvonicek** [comment]
Thanks for reporting this, I've commited a fix.
