### ISSUE TITLE
How to use currentPageChanged?

### ISSUE THREAD

**Issue by meanreaksmey** [zvonicek/ImageSlideshow#118]

**Comment by dogo** [comment]
```swift
slideshow.currentPageChanged = { page in
     // do whatever you want eg:
     self.navigationItem.title = self.cards[page].name
}
```

**Comment by Niroj08** [comment]
i cannot find that :/

**Comment by Niroj08** [comment]
Can anyone ad the feature on branch swift-2.3 
 /// Called on each currentPage change
    open var currentPageChanged: ((_ page: Int) -> ())?

**Comment by zvonicek** [comment]
Hi, I'm sorry, the branch `swift-2.3` is not developed anymore so we're not adding any new features to it. You can check `master` branch and backport this feature to Swift 2.3 yourself if you want.
