### ISSUE TITLE
If you have anytime,can you do image caching with alamfireImage?

### ISSUE THREAD

**Issue by htarwara6245** [zvonicek/ImageSlideshow#12]
If you embedded your image slide show library with : https://github.com/Alamofire/AlamofireImage
It will be awesome and many people gonna start use this because its essential,you know.Now,I am working on,If I can,I will contribute.

**Comment by zvonicek** [comment]
I've just added _AlamofireSource_ for downloading images via AlamofireImage. Let me know if you spot any issues with that.
