### ISSUE TITLE
Add Activity Loader on each Image of the Slideshow

### ISSUE THREAD

**Issue by vaibhav-varshaaweblabs** [zvonicek/ImageSlideshow#123]
Is there a way to add a Activity Loader to each image of the slideshow until the image is fully loaded?

**Comment by htarwara6245** [comment]
Duplicates Question : 

[https://github.com/zvonicek/ImageSlideshow/issues/13](url)

**Comment by zvonicek** [comment]
Ok, I finally implemented this 🎉 Already available in master, new release will be made soon.
