### ISSUE TITLE
How can I put some text on imageslideshow?

### ISSUE THREAD

**Issue by luthfifr** [zvonicek/ImageSlideshow#124]
Hi, I want to put some text on imageslideshow view, so that it could be one of these images:
![photo 2-24-17 06 38 20](https://cloud.githubusercontent.com/assets/22187764/23284432/10cb5592-fa5e-11e6-8165-f89916250621.jpg)

How can I do that? Thanks.

**Comment by zvonicek** [comment]
Hi, thanks for the suggestion. This is duplicate with #55, we can continue with discussion there. This feature is definitely on the list, although it's not top priority right now.
