### ISSUE TITLE
Duplicated images

### ISSUE THREAD

**Issue by aliakkawi** [zvonicek/ImageSlideshow#126]
Please help, i have a lrage amount of images, about 500 images, and making a for loop to add the images to an array is causing a memory issue and app terminating, 
so as a workaround i've added 2 images to the array at the beginning, and then using "currentPageChanged" closure i am appending a new image to my array , and then i am setting  again the image inputs, the problem is that the images are duplicating as i scroll forth and backwards. Please advice me what to do.
I've attached a file with my code. I really need help with this
Thanks a lot
[My code.txt](https://github.com/zvonicek/ImageSlideshow/files/810818/My.code.txt)

**Comment by zvonicek** [comment]
Hi! First, please try to adjust preloading to not load all 500 images at once, for example:

`imageSlideshow.preload = .fixed(offset: 5)`

This could help you with the memory issue.

**Comment by htarwara6245** [comment]
This issue should be close by now.

**Comment by pratikgajbhiye222** [comment]
> Please help, i have a lrage amount of images, about 500 images, and making a for loop to add the images to an array is causing a memory issue and app terminating,
> so as a workaround i've added 2 images to the array at the beginning, and then using "currentPageChanged" closure i am appending a new image to my array , and then i am setting again the image inputs, the problem is that the images are duplicating as i scroll forth and backwards. Please advice me what to do.
> I've attached a file with my code. I really need help with this
> Thanks a lot
> [My code.txt](https://github.com/zvonicek/ImageSlideshow/files/810818/My.code.txt)

Have you find the solution
?
