### ISSUE TITLE
error install pod file

### ISSUE THREAD

**Issue by J-Arji** [zvonicek/ImageSlideshow#128]
hi when install pod file
xcode7.3 and swift2.3
```
[!] There are multiple dependencies with different sources for `ImageSlideshow` in `Podfile`:

- ImageSlideshow/Alamofire (from `https://github.com/zvonicek/ImageSlideshow.git`, branch `swift2.3`)
- ImageSlideshow (~> 0.5)
```

**Comment by zvonicek** [comment]
Hi, please try to remove the `ImageSlideshow, '~> 0.5'` from your Podfile. `ImageSlideshow/Alamofire` should also install the ImageSlideshow itself.

**Comment by J-Arji** [comment]
remove  ImageSlideshow, '~> 0.5'
and install again but error: 
```
[!] Unable to satisfy the following requirements:

- `AlamofireImage (~> 3.0)` required by `ImageSlideshow/Alamofire (1.1.0)`

None of your spec sources contain a spec satisfying the dependency: `AlamofireImage (~> 3.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by J-Arji** [comment]
thank you update pod repo and The problem was solved

**Comment by J-Arji** [comment]
I install when I want `pod 'ImageSlideshow/Alamofire', :git => 'https://github.com/zvonicek/ImageSlideshow.git'`
Install the latest version of them But I would like to install for swift 2.3
I thank you guide me how can i do it

**Comment by raghad54** [comment]
Hello @zvonicek 
I'm trying to use   pod "ImageSlideshow/Alamofire", :path => "../" in my Project but CocaPods reply : [!] No podspec found for `ImageSlideshow` in `../`
this my podFile
 # Pods for ......
   pod 'IQKeyboardManagerSwift'
   pod 'CHIPageControl/Jaloro'
   pod 'Cosmos', '~> 20.0'
   #pod 'ImageSlideshow', '~> 1.8.3'
   pod 'ARSLineProgress'
   pod 'ReachabilitySwift'
   #pod 'DropDown'
   pod 'Kingfisher'
   pod 'DLRadioButton'
   pod 'MessageKit'
   pod 'BetterSegmentedControl', '~> 1.3'
   pod 'Firebase/Core'
   pod 'Firebase/Messaging'  
   pod 'FirebaseStorage'
   pod 'Firebase/Firestore' 
   pod 'Alamofire', '~> 5.1'
   pod "ImageSlideshow/Alamofire", :path => "../"
end

How Can I Solve it ?
