### ISSUE TITLE
how can install imageSlideshow for swift 2.3

### ISSUE THREAD

**Issue by J-Arji** [zvonicek/ImageSlideshow#129]
hi 
how can install this library for swift 2.3 ?
 i used from this line but not working true 
`pod 'ImageSlideshow/Alamofire', :git => 'https://github.com/zvonicek/ImageSlideshow.git'
`
 thank you for help

**Comment by zvonicek** [comment]
Hi, we discussed this in #128. Either use branch `swift2.3`, or version `0.5` from CocoaPods.

**Comment by J-Arji** [comment]
hi when that i use  `pod "ImageSlideshow/Alamofire" , :branch => 'swift-2.3'`

error :` [!] Unknown external source parameters for `ImageSlideshow`: `{:branch=>"swift-2.3"}``

**Comment by J-Arji** [comment]
thank you for help 👍
