### ISSUE TITLE
Feature Request : Activity Indicator and Retry Button

### ISSUE THREAD

**Issue by htarwara6245** [zvonicek/ImageSlideshow#13]
Feature Request(For more imporvement of this library)
1.Adding Activity Indicator for loading the image before it finished downloading on both slideshow and zoomview and let us adding placeholder image by our self.

2.If the Image download failed because of connection?Any feature for retry button?

Thanks for helping me.I hope you got my feature request,too.It will be perfect this time.And permission to share this library on SO because many people are hoping to get this.Thanks.

**Comment by zvonicek** [comment]
I still plan to implement this feature when have more time. Just writing down a related task to analyse possible error handling ways so user of the library can observe and react to them.

**Comment by zvonicek** [comment]
Ok, I finally implemented this 🎉 Already available in master, new release will be made soon.
