### ISSUE TITLE
UIApplicationWillChangeStatusBarFrameNotification Support

### ISSUE THREAD

**Issue by htarwara6245** [zvonicek/ImageSlideshow#132]
The Full Screen Slide View need support for this as well. When I close the full screen, slide view and its root view controller slidely down a bit which was not normal for status bar frame situation when we tether our phone internet.

**Comment by zvonicek** [comment]
Hi @htarwara6245, good catch, Full Screen Controller really jumps down a bit when In-Call status bar is on. Would you mind creating a pull request fixing this?

**Comment by htarwara6245** [comment]
I will take a look into. But, notice, this also affect to slideshow(UIView) included UIViewController which was not full screen view which I am wondering why.
