### ISSUE TITLE
slideshowItems Array contains 2 more ImageSlideshowItems than I added

### ISSUE THREAD

**Issue by DominikButz** [zvonicek/ImageSlideshow#136]
Hi,
I create an image slideshow in each table view cell.  I add my own image sources called FirebaseImageSource.  
for example like this: 
 var inputSourceArray:[FirebaseImageSource] = []
            
            for url in photoURLs {
                inputSourceArray.append(FirebaseImageSource(urlString: url)!)
            }

  self.imageSlideshow.setImageInputs(inputSourceArray)

up until this point all works fine. 

Tapping on a cell triggers a segue to a detail vc where I create another image slideshow with the same images as the tapped cell. for efficiency reasons, it doesn't make sense to re-download the same images again.    
in prepare for segue I do the following logic:

 var photoArray:[UIImage] = []
            for item in cell.imageSlideshow.slideshowItems {
                if let image = item.imageView.image  {
                   // print("appending image")
                    photoArray.append(image)
                }
            }

To my surprise, the number of images (and also Image slideshow items) are 2 more than the image urls.  Still, the tableview cells show the correct number of images (e.g. 3).  but the image slideshow in the detail view shows 5 images but there are only three images urls ...   Is this a bug?  actually the first two images are repeated at the end. 
if there  is only one image url, both image slideshows show 1 image correctly. but if there are 2 images, the same two image items are added again. 

thanks for any hints.

**Comment by DominikButz** [comment]
OK, I figured it out... in circular mode, there are two two of the items repeated at the end and the beginning of the array... 

To extract the images from the image slideshow in the TV cell, fixed it like this:

var photoArray:[UIImage] = []

   for item in cell.imageSlideshow.slideshowItems {
                if let image = item.imageView.image  {
                    photoArray.append(image)
                }
     } 
            if cell.imageSlideshow.circular  && cell.imageSlideshow.slideshowItems.count > 1 {
                
                photoArray.removeLast()
                photoArray.removeFirst()
                
            }

**Comment by zvonicek** [comment]
Those two extra items are put to circular slideshow intentionally to provide smooth scrolling between edge (first and last item). You should not remove those items, otherwise scrolling issues might appear.

But in general you should not need to care about efficiency this way, most image loading libraries like AlamofireImage or SDWebImage provides caching so the full screen image will be loaded from cache.

**Comment by DominikButz** [comment]
Thanks - I'm using Firebase here and therefore had to create my own class conforming to InputSource protocol. I will see how to get them from cache if I can access it. Till then, the workaround works fine. I don't change the content of the slideshowItems array but only copy the images .
