### ISSUE TITLE
Slideshow Stops Transitionining

### ISSUE THREAD

**Issue by samhinsh** [zvonicek/ImageSlideshow#138]
Hi, I'm using the slideshow and it only makes one transition for me (regardless of the time interval I've set, or how many images I've loaded in the input array). I have the slideshow in multiple places in my app, and this happens in every single place. I've tried mirroring the example given as closely as possible. 

Thanks!

**Comment by zvonicek** [comment]
Hi! Could you please share your example project? I haven't experienced this issue before and cannot reproduce it on my side.

**Comment by Mbt925** [comment]
I've encountered this problem too.

`self.slideShow.setImageInputs(slideImages)
        self.slideShow.contentScaleMode = .scaleAspectFill
        self.slideShow.slideshowInterval = 500
        self.slideShow.zoomEnabled = true
        self.slideShow.pageControlPosition = .hidden
        self.slideShow.activityIndicator = DefaultActivityIndicator(style: .whiteLarge, color: .black)`

**Comment by zvonicek** [comment]
@Mbt925 I'm sorry I still can't see the problem. I tried your code but automatic transition works correctly there...

**Comment by Mbt925** [comment]
I am using AlamofireSource.

**Comment by zvonicek** [comment]
I've been trying it with AlamofireSource too. Ideally, send me an example project demonstrating the problem and I'll look into it.

**Comment by Mbt925** [comment]
I assumed `slideshowInterval` was in milliseconds (`self.slideShow.slideshowInterval = 500`). But it seems it's in seconds. Am I correct?

**Comment by scottcc** [comment]
`NSTimeInterval` is indeed seconds (use fractions for sub-seconds). Sounds like you have found the root issue there.

**Comment by zvonicek** [comment]
Oh, `slideshowInterval` is indeed in seconds. Sorry for the confusion, it's my fault it was not explicitly mentioned in the docs. Fixed it. 
I think I can now close the issue, let me know if there are any further issues.
