### ISSUE TITLE
How to make scrollview work when working on Universal (Adaptive Layout)?

### ISSUE THREAD

**Issue by htarwara6245** [zvonicek/ImageSlideshow#14]
I am experiencing like scroll images are bouncing when I add scrollview to my project.Please take a look

But,when i disable Extend Edges (Under Top Bar and Under Button Bar) scroll work fine(No image bouncing).

Is there any way to work under Navigation bar and tab view?Please Take a look
![sliding view](https://cloud.githubusercontent.com/assets/10526402/12345614/970cb968-bb79-11e5-98b4-0f615231d8bd.gif)

And for my storyboard
http://puu.sh/mwdSR/7a14fee591.png

Did I do anything wrong?Please Help?

**Comment by htarwara6245** [comment]
I will be waiting for that bug fix m8,Thanks.

**Comment by htarwara6245** [comment]
Any help pls?I have been waiting for that?Or should I use it by disabling extend edges on storyboard viewcontroller?

**Comment by zvonicek** [comment]
Could you please check if this issue is still present?
