### ISSUE TITLE
Update for Swift 3.1?

### ISSUE THREAD

**Issue by seenoevo** [zvonicek/ImageSlideshow#141]
I seem to be getting an import error when I updated from Swift 3.0 to Swift 3.1

Xcode is complaining that:

> Module compiled with Swift 3.0.1 cannot be imported in Swift 3.1

on the code `import ImageSlideShow`

does the code need to be updated to support Swift 3.1?

if so, please update asap as this is preventing me from working further on my app :(

**Comment by NaiyerAghaz** [comment]
i am facing same problem with this code please update asap

**Comment by zvonicek** [comment]
Hi, how do you integrate ImageSlideshow into your app? ImageSlideshow itself works correctly on Swift 3.1, it just seems you use dylib build for Swift 3.0 instead of Swift 3.1.

**Comment by seenoevo** [comment]
@zvonicek all I did was manually copy the appropriate files and framework as mentioned by the instructions into my Swift 3.1 project directory

**Comment by zvonicek** [comment]
Ok, I see. Please hold on for a while, I'm going to release a new version very soon and will build the  dynamic framework for Swift 3.1.

**Comment by zvonicek** [comment]
Version 1.3.0 is out and the attached framework should be Swift 3.1 compatible. Check that out!
