### ISSUE TITLE
Coming back from Full screen in Landscape, gets the app to portrait.

### ISSUE THREAD

**Issue by anamalihassan** [zvonicek/ImageSlideshow#142]
I am using ImageSlideshow in UIScrollView. It works fine in the portrait mode. But when I rotate to landscape mode and then go to full screen to view images, when I tap cancel and come back, the whole app gets rotated to portrait even though I am holding device in landscape mode. Also half of the view is black. Please view the simulator screen shot for the reference. Facing same issue on the device as well.
![simulator screen shot apr 19 2017 10 55 24 am](https://cloud.githubusercontent.com/assets/6736733/25167138/53186ce4-24ef-11e7-8016-e2b78766f8dd.png)

**Comment by htarwara6245** [comment]
It will be helpful if you share an example project of causing this.

**Comment by anamalihassan** [comment]
I using this library in a very simple way. In story board I am using [autolayouts](http://stackoverflow.com/questions/38948904/calculating-contentsize-for-uiscrollview-when-using-auto-layout). Sliding view has constraints of leading and trailing space to 60 & height equal to 291. Below is the code for image sliding: `imagesSV.backgroundColor = UIColor.white
        imagesSV.slideshowInterval = 5.0
        imagesSV.pageControlPosition = PageControlPosition.insideScrollView
        imagesSV.pageControl.currentPageIndicatorTintColor = UIColor.lightGray
        imagesSV.pageControl.pageIndicatorTintColor = UIColor.black
        imagesSV.contentScaleMode = UIViewContentMode.scaleAspectFill
        imagesSV.currentPageChanged = { page in
//            print("current page:", page)
        }
        imagesSV.contentScaleMode = .scaleAspectFit
        // try out other sources such as `afNetworkingSource`, `alamofireSource` or `sdWebImageSource` or `kingfisherSource`
        imagesSV.setImageInputs(localSource)
        
        let recognizer = UITapGestureRecognizer(target: self, action: #selector(PDSummaryVC.didTapImagesSlider))
        imagesSV.addGestureRecognizer(recognizer)

    
    func didTapImagesSlider() {
        imagesSV.presentFullScreenController(from: self)
    }`

**Comment by htarwara6245** [comment]
May be it's autolayout or something else which u might make the device which force to landscape -> portrait. If you are doing that, please refer to this question => 

http://stackoverflow.com/questions/28938660/how-to-lock-orientation-of-one-view-controller-to-portrait-mode-only-in-swift

Try show us the current state using : http://www.cockos.com/licecap/ 
or it will be helpful if you share your example project so we can look into your storyboard or codes
