### ISSUE TITLE
Additional Configuration

### ISSUE THREAD

**Issue by A-w-K** [zvonicek/ImageSlideshow#143]
Do you plan on adding additional configurations like scroll duration (how slow/fast it autoscrolls to the next page, not the interval timer) or different animations?

**Comment by zvonicek** [comment]
Hi! If there's an interest I could consider a possibility to change scroll interval, but it's not a priority now. As for the different animations, which one do you mean? The full screen present/dismiss transition? This one is fully configurable by implementing your own transition delegate.

**Comment by CIOPinal** [comment]
can you add fade in animation for image slideshow?
