### ISSUE TITLE
"Open" access control for "UIScrollViewDelegate" methods

### ISSUE THREAD

**Issue by Kumuluzz** [zvonicek/ImageSlideshow#145]
I want to subclass `ImageSlideshow` and make a few minor view modifications and animations. In particular I'd like to overwrite `ImageSlideshow.scrollViewDidEndDecelerating(_:)` in order to make an animation when the slideshow stops at a given image.

Currently the `ImageSlideshow` class implements the following three methods from `UIScrollViewDelegate`:
- `ImageSlideshow.scrollViewWillBeginDragging(_:)`
- `ImageSlideshow.scrollViewDidEndDecelerating(_:)`
- `ImageSlideshow.scrollViewDidScroll(_:)`

These implementations have been done with a `public` access control, which prevents overriding them in a subclass. 

I propose to change these three method implementation to an `open` access control level instead.

**Comment by zvonicek** [comment]
Hi @Kumuluzz, thanks for the issue and the pull request! 🎉 This seems to be very reasonable, I'm merging it to master.

**Comment by Kumuluzz** [comment]
🎉🎉🎉
