### ISSUE TITLE
Network images loading

### ISSUE THREAD

**Issue by johnnyoin** [zvonicek/ImageSlideshow#149]
Hi there,

I was wondering if you thought about adding a loading indicator to downloading pictures, especially for slow networks.

Anyway thanks a lot for this great lib.

**Comment by RizkiMufrizal** [comment]
same issue for me

**Comment by Mbt925** [comment]
And for me

**Comment by zvonicek** [comment]
Hi there! Good news, this was implemented just a week ago and is pending a release, which I hope to make today.

(was discussed in #13 before)

**Comment by zvonicek** [comment]
Version 1.3.0 is out, check that out!
