### ISSUE TITLE
Feature Request: Show Current Image Index Instead of Page Controller

### ISSUE THREAD

**Issue by Mbt925** [zvonicek/ImageSlideshow#151]
Thanks for the great library.

It would be great if we could switch between displaying page controller and a label showing current image index (something like: [3/15]).

**Comment by zvonicek** [comment]
Hi, this is unfortunately not currently supported in the library, but you can even make this label yourself. Just add your own label as a subview to ImageSlideshow and listen to `currentPageChanged` closure changes to update it with the current image index.
