### ISSUE TITLE
Activity indicator disappears on scroll

### ISSUE THREAD

**Issue by tdimeco** [zvonicek/ImageSlideshow#152]
Hello,

Thank you for your last update with the activity indicator, it's very useful!

I faced an issue with the loader: if I open a `FullScreenSlideshowViewController`, the loader appears correctly, but if I scroll to the next picture and then I scroll back immediately to the previous one, the loader is gone.

Is it a bug?

Thanks!

– Thomas

**Comment by johnnyoin** [comment]
I'm also experiencing this issue. It also seems that when a picture finishes loading, other indicators are hidden.

E.g. I scroll to a picture, and immediately scroll to the next one. When the first picture finished loading the second indicator is hidden but the picture is still loading.

**Comment by zvonicek** [comment]
Hi, thanks for the report and sorry for problems. I've attempted to fix the issue in b83bdd9, cloud you apply changes in this commit to your project (or let the CocoaPods get the code from the `master` branch) to see if it helps?

**Comment by johnnyoin** [comment]
Yep, it solves the problem in my case.

**Comment by tdimeco** [comment]
Me too! Thx! :)

**Comment by zvonicek** [comment]
Thanks, guys. I released a new version 1.3.1 with the fix.
