### ISSUE TITLE
AspectFill not working sometimes

### ISSUE THREAD

**Issue by Mbt925** [zvonicek/ImageSlideshow#153]
I configured ImageSlideshow to show images as AspectFill. I am using AlamofireSource for loading my images into ImageSlideshow. But Sometimes, the image does not appear as AspectFill as can be seen in the attached image.

![aspectfill](https://cloud.githubusercontent.com/assets/10066112/25898659/4d2b3b4a-35a2-11e7-9940-846707b86a40.png)

**Comment by zvonicek** [comment]
I've just pushed a change that might fix the issue, please check the commit b83bdd9, try to apply those changes to your project and let me know if it helps your issue.

**Comment by Mbt925** [comment]
I checked it. The problem still exists.

**Comment by Mbt925** [comment]
It happens when `zoomEnabled = true`.

**Comment by zvonicek** [comment]
I'm still not able to reproduce the problem. Please share a steps to reproduce the bug with me so I can check it.

**Comment by Mbt925** [comment]
Set scale mode to `scaleAspectFill` and then, enable `zoom`.
