### ISSUE TITLE
AlamofireSource for self signed certs

### ISSUE THREAD

**Issue by iad24** [zvonicek/ImageSlideshow#157]
How to configure your AlamofireSource to show images from server with self signed certs?

**Comment by zvonicek** [comment]
Hi, this is more a question for the Alamofire. ImageSlideshow is just a wrapper over AlamofireImage.

**Comment by iad24** [comment]
Yeah. I noticed your wrapper is just the basic one. So I created  my own InputSource that uses my configured Alamofire Manager (that can download images from self signed server).

But still good job on this one! =) I chose yours over others cos you got the auto slide show.

**Comment by zvonicek** [comment]
Yep, the wrapper is just the basic one, but it's easy to create your own one and users are encouraged to do so!
