### ISSUE TITLE
option to add page control on the left side instead of just center?

### ISSUE THREAD

**Issue by iad24** [zvonicek/ImageSlideshow#158]
can have this? thanks

**Comment by zvonicek** [comment]
This was discussed before in #93. I investigated this case and found out I'd need to rewrite the way page control position is handled, which would be a breaking change for other users. 
I definitely plan to implement this, but for now I'd recommend to adjust the `pageControl` frame yourself.

**Comment by zvonicek** [comment]
I've finally implemented more page indicator positioning flexibility in #251! Now you can easily set the position to left using `PageIndicatorPosition(horizontal: .left, vertical: .under)`.
