### ISSUE TITLE
ContentSize bug with zoom

### ISSUE THREAD

**Issue by johnnyoin** [zvonicek/ImageSlideshow#159]
ContentSize seems broken when image is zoomed, especially in fullscreen with landscape pictures.

I'm pretty sure a5e56615b7df6edc42d4bcf0865f4d3976514158 has something to do with it, but I think I already encountered this bug before.

To reproduce: run the example, go fullscreen, double tap and swipe up or down

**Comment by zvonicek** [comment]
Thanks for the report, I fixed the issue in the latest 1.3.2 version. Please check it and let me know if you spot any further issues.
