### ISSUE TITLE
The slideshow cannot display image file without jgp file extension

### ISSUE THREAD

**Issue by ihomecall** [zvonicek/ImageSlideshow#16]
I have an image url as
http://files.parsetfss.com/181dfc1b-0f21-4364-b87f-830ad854a26a/tfss-3a1e735b-1f54-46df-a493-ce8e3b47c2ce-file

when I put this to the imageslide, it does not show up... why?    Is that because the file has no extension?

any help?

Thanks

**Comment by ihomecall** [comment]
it is related to this function setImageWithURLRequest, which don't load the file it has no file extension....Why not?

**Comment by htarwara6245** [comment]
Ok let me check.Are you using AFURLsource or Alamofiresource?

**Comment by ihomecall** [comment]
Thanks. 6245.    I am using AFURLsource.

cannot wait for your answer -:)

**Comment by zvonicek** [comment]
As you mentioned, this lib uses _setImageWithURLRequest_ from _AFNetworking_ to load the image. The problem is therefore not related to this library, but to the way you're downloading your file. You should check out documentation of the backend service you're using for more info.
