### ISSUE TITLE
Full Screen Slideshow - Auto Rotate Image

### ISSUE THREAD

**Issue by vaibhav-varshaaweblabs** [zvonicek/ImageSlideshow#165]
I need the Image Slideshow in Fullscreen to rotate with Device rotation.

All other View Controllers in my App should e compulsory in Portrait mode, only the full-screen gallery of Image slideshow should Auto Rotate

Please help !!!

**Comment by msavula** [comment]
If you're presenting Slideshow modally, you can achieve that by implementing app delegate's method
```
func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
        if window?.rootViewController?.presentedViewController is SlideshowController {
            return .all
        }
        
        return .portrait
    }
```

please note, that with this approach your app will be in landscape, if you close slideshow in landscape orientation, if you wish to avoid this, you should present slideshow in a separate window AND implement app's delegate method like:

```
func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
        if window != self.window {
            return .all
        }
        
        return .portrait
    }
```
