### ISSUE TITLE
[Request] Fade in FullScreen animation

### ISSUE THREAD

**Issue by L4grange** [zvonicek/ImageSlideshow#170]
Hello. Thank you for your amazing library. I'm creating an app and I'm using this to show all the photos inside the articles I fetch from websites.

I fill my ImageSlideShow with all the images that are inside the article with works great.

My UI goes like this: There is a Scrollview that contains an ImageSlideShow at the top and under it there is a WebView containing the article, so the user can scroll everything while reading the article.

When the user taps an image inside the webView, I present the FullScreenSlideShowViewController. However, since the slideshow is at the top, when it is not visible, the animation looks weird, since the image "accelerates" from the top of the scrollView towards the centre of the screen.

Is there a way to either disable the animation, or add a "fade in from the center" to the FullScreenSlideShow?

I can detect when the SlideShow is visible, I just need to be able to either disable the animation completely, or use a fade in one.

Thank you!

**Comment by aofeng2009** [comment]
Me too

**Comment by L4grange** [comment]
I tries modifying the existing zoom animation but failed, I'll try again when I have the time and let you know of any progress. If anyone else can offer any help it will be very much appreciated!

**Comment by zvonicek** [comment]
I'm sorry for being late to the game, but I'm sending a solution in case soneone else would need it. The key is not to use `slideshow.presentFullScreenController` in this case, but write the presentation logic manually. Fade animation can be done by setting appropriate `modalTransitionStyle` property.

```swift
    @objc func didTap() {
        let fullscreen = FullScreenSlideshowViewController()
        fullscreen.pageSelected = {[weak self] (page: Int) in
            self?.slideshow.setCurrentPage(page, animated: false)
        }

        fullscreen.initialPage = slideshow.currentPage
        fullscreen.inputs = slideshow.images
        fullscreen.modalTransitionStyle = .crossDissolve
        self.present(fullscreen, animated: true, completion: nil)
    }
```
