### ISSUE TITLE
General Query

### ISSUE THREAD

**Issue by 0x6d6e** [zvonicek/ImageSlideshow#172]
Hello,
This is a great library and I am really enjoying using this.
 A general query here..I did a pod update on the latest version but I dont see the KingFisherResource in the Pod checked out on my project? Has this been removed? I do see the KingFisherResource file in the project directory, but not in my pod checkout. Am I missing something?

Thanks

**Comment by photos** [comment]
Don't fret, add pod "ImageSlideshow/Kingfisher" to your podfile!
