### ISSUE TITLE
Insert ImageInputs on FullScreen

### ISSUE THREAD

**Issue by zakumito** [zvonicek/ImageSlideshow#173]
Hi,

On full screen when the user reaches the last image I add more image inputs using setImageInputs to the slideshow of the fullscreen view controller. Everything goes well except the new added images are not in full screen. When I tap it they zoom and the size fixes. There is something that I have to do to solve this?

Related with: [#106](https://github.com/zvonicek/ImageSlideshow/issues/106)

Thanks!

**Comment by chuwito** [comment]
I resolved the issue modifying loadImage in ImageSlideshowItem:

`/// Request to load Image Source to Image View
    func loadImage() {
        if self.imageView.image == nil && !isLoading {
            isLoading = true
            imageReleased = false
            activityIndicator?.show()
            image.load(to: self.imageView) { image in
                // set image to nil if there was a release request during the image load
                self.imageView.image = self.imageReleased ? nil : image
                self.activityIndicator?.hide()
                self.loadFailed = image == nil
                self.isLoading = false
                self.layoutSubviews() // <- Adding this solves the scale problem
            }
        }
    }`
