### ISSUE TITLE
Display Page control below the image.

### ISSUE THREAD

**Issue by venkadesh02** [zvonicek/ImageSlideshow#174]
I want to display page control below the image view. According to this link https://github.com/zvonicek/ImageSlideshow/issues/93 i tried setting frame for page control like as follows,

    self.imageSlideshow.pageControl.frame = CGRect(x: 0, y: 150, width: view.frame.width, height: 30)

But its not changing the page control position. Can anyone help me to fix this?

**Comment by greatsk55** [comment]
i think 
self.imageSlideshow.pageControl.frame = CGRect(x: 0, y: 150, width: view.frame.width, height: 30)
is input below to
 imageSlideshow.setImageInputs()

**Comment by Kam21** [comment]
You can set the padding  :
slideshow.pageControlPosition = PageControlPosition.custom(padding: 15)
