### ISSUE TITLE
How to add ImageSlideshow on StoryBoard?

### ISSUE THREAD

**Issue by fash97** [zvonicek/ImageSlideshow#175]
Although I installed it pod, I still cannot find it in the object library.
Could anyone help me? I am new to Swift..

**Comment by centell** [comment]
I have the same problem too. When I search 'Image' in Main.storyboard, I get only 'Image View'.

**Comment by edd677** [comment]
You need to add a UIView from the Object Library, then set the subclass to ImageSlideshow in the Object Inspector. Then import the framework into the view controller as you would with any pod.

Hope this helps!

**Comment by bernaferrari** [comment]
If you still have trouble, I recommend downloading the project and copy and pasting the ImageSlideshow from the sample app into your app.

**Comment by centell** [comment]
@bernaferrari haha It works well. Thank you! 
@edd677 I Try it, and I met  < use of unresolved identifier 'slideshow' > (T^T)

**Comment by fash97** [comment]
@edd677 
@bernaferrari 
Thanks, guys! Super newbie here :)

**Comment by edd677** [comment]
@centell you need to create an IBOutlet from your UIView in your View Controller and call it "slideshow". You can obviously call it something different, just change the reference in the example code from "slideshow" to whatever you chose to call the outlet.

**Comment by centell** [comment]
@edd677 Thank you for your kindness!
