### ISSUE TITLE
Can I change the type of pageControl to a number?

### ISSUE THREAD

**Issue by centell** [zvonicek/ImageSlideshow#176]
If there are many pictures, the dot type pageControl will fill the screen and will not function again. 
I read " https://github.com/zvonicek/ImageSlideshow/issues/26  " and it seems to be difficult to write this way.
Can I chage it numeric pageControl? like  " 1 / 36 ", " 2 / 36 " ..?

**Comment by scottcc** [comment]
I'll comment here as I had the same problem - it wasn't too hard to simply build a square UIView with a single label, round the corners, then use snapkit to center it horizontally and offset from the bottom:

![circle1](https://user-images.githubusercontent.com/225380/28214177-334982ec-6877-11e7-8d67-4bbf555d9114.png)

Then when going fullscreen, use SnapKit instead to centre the vertical sphere to the helpfully-exposed `closebutton`

![circle2](https://user-images.githubusercontent.com/225380/28214212-583e1a40-6877-11e7-82db-4737efd51105.png)

If the project owner felt that was worthwhile (and is OK with the SnapKit dependency addition) I could consider adding that into a PR.

**Comment by centell** [comment]
@scottcc I am sorry I'm late. I first learned about snapkit. Thank you!

**Comment by centell** [comment]
I found another way.  
https://github.com/shima11/FlexiblePageControl

**Comment by scottcc** [comment]
Very nice @centell - hadn't seen that control, very nice. I do see that it's a `UIView` subclass as opposed to a `UIPageControl` subclass - but that does seem to be the way for most cool newer-kinds of page controls. Thanks for sharing!

**Comment by zvonicek** [comment]
So, finally a follow-up from me 😄 

I've implemented a `PageIndicatorView` protocol in #251 that anyone can adopt to use their own page indicator. It can easily be used in combination with any other UI component, like FlexiblePageControl. Also, a simple numeric page indicator, `LabelPageIndicator`, showing just page numbers, is provided.
