### ISSUE TITLE
can I add an image to show image download failure

### ISSUE THREAD

**Issue by A-jay98** [zvonicek/ImageSlideshow#177]
how can i add image to show when image download failed or link was broken , with tap to reload ability

**Comment by wemamark** [comment]
You can manually add an InputSource class to your project (the sources of the shipped InputSources can be found in _**/ImageSlideshow/Classes/InputSources/**_ in this GIT repo) and change the load() function to trap and handle downloading errors.

For example, in SDWebImageSource, you could change the completion block from
```
completed: { (image, _, _, _) in
    callback(image)
})
```

to
```
completed: { (image, _, _, _) in
    guard let image = image else {
        callback(insert your fail image here)
        return
    }

    callback(image)
})
```

Or, if you're using AlamoFireImage, you could change the completion block from
```
{ (response) in
    callback(response.result.value)
}
```
to
```
{ (response) in
    switch response.result {
    case .success(let value):
        callback(value)
        break

    case .failure(let value):
        callback(insert your fail image here)
        // call a user-defined error handler if you like
        break
    }
}
```

I'll leave the rest up to you :)
