### ISSUE TITLE
How to go throught images tapping next and back buttons?

### ISSUE THREAD

**Issue by AbrahamEP** [zvonicek/ImageSlideshow#178]
How can I do this?

**Comment by haemi** [comment]
did you find a solution? Currently I try with

`setCurrentPage(currentPage + 1, animated: true)`

and 

`setCurrentPage(currentPage - 1, animated: true)`

but the behavior is weird...

**Comment by tkirby** [comment]
Next works fine but previous fast-forwards to the end when you do:

`setCurrentPage(currentPage - 1, animated: true)
`

**Comment by tkirby** [comment]
I created a subclass of  the ImageSlideShow class and was able to get the previous button to work using this:

 ```
@IBAction func previous()
    {
        if scrollViewPage == 0
        {
            setScrollViewPage(items.count, animated: false)
        }

        setCurrentPage(currentPage - 1, animated: true)
    }
```
where items is me keeping an array of the images I add to the slideshow so I know the count.

**Comment by zvonicek** [comment]
I implemented `previousPage` and `nextPage` methods on ImageSlideshow in 31710dbed4e7b13fb8274b985e8b6addf358f257
