### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by lotfyahmed** [zvonicek/ImageSlideshow#182]
How to change dots and selected one colors?

I tried the following code but there is an error:
slideshow.activityIndicator = DefaultActivityIndicator(style: .white, color: nil)

![screen shot 2017-08-13 at 9 34 49 am](https://user-images.githubusercontent.com/3439991/29247698-bd94f54e-800a-11e7-9103-445f16ebdaf2.png)

I want the following colors:
![screen shot 2017-08-13 at 9 36 02 am](https://user-images.githubusercontent.com/3439991/29247711-e6d64598-800a-11e7-9035-b03e9b6589cb.png)

Please help me.

**Comment by jonjes468250** [comment]
you can use 
.pageControl.currentPageIndicatorTintColor &.pageControl.pageIndicatorTintColor

**Comment by lotfyahmed** [comment]
Thanks
