### ISSUE TITLE
slideshowTick crash

### ISSUE THREAD

**Issue by Blankz** [zvonicek/ImageSlideshow#187]
my app just crash at imageSlideshow.swift line 352
specialized ImageSlideshow.slideshowTick(Timer) -> ()

idk why app crash

**Comment by zvonicek** [comment]
Can you share an example project reproducing this issue? Thanks.

**Comment by Blankz** [comment]
because  scrollView.contentOffset.x / scrollView.frame.size.width  = nan 
cannot convert to Int 

var page = 0
       if scrollView.contentOffset.x / scrollView.frame.size.width > 0 {
            page = Int(scrollView.contentOffset.x / scrollView.frame.size.width)
        }

**Comment by aofeng2009** [comment]
Me too , scrollView.frame.size.width is 0.

**Comment by AhmedSalahAli** [comment]
it crash times cant find pod after working and i have to remove and install again to work

**Comment by zvonicek** [comment]
@Blankz thank you for the analysis, I pushed a fix for this problem.
