### ISSUE TITLE
ImageSlideShow still working after I pop or dismiss the viewcontroller.

### ISSUE THREAD

**Issue by jack45j** [zvonicek/ImageSlideshow#189]
I have an ImageSlideshow in viewcontrollerB. The issue is ImageSlideshow still working after I pop, dismiss even I unwind viewcontrollerB back to viewcontrollerA.
When I push to viewcontrollerB again and then pop it back to viewcontrollerA.
The currentPageChanged method still working and it fired twice each time.
I have no idea. Did I miss something?

**Comment by zvonicek** [comment]
Hi, it seems like you have a memory leak in your code. Check you use the weak references when necessary, especially in the `pageSelected` closure.

**Comment by jack45j** [comment]
Yes you are right!! Finally I solved the problem.
Thank you so much. You are awesome!
