### ISSUE TITLE
Respecting the safe zone on iPhone X

### ISSUE THREAD

**Issue by mdilaveroglu** [zvonicek/ImageSlideshow#193]
Page control goes under the bottom line.

![simulator screen shot - iphone x - 2017-09-27 at 17 06 48](https://user-images.githubusercontent.com/6029299/30918790-3c1f20fe-a3a8-11e7-8c0b-84bda9382488.png)

**Comment by zvonicek** [comment]
Hi, check out the version 1.4.1, I added support for the safeAreaInsets.
