### ISSUE TITLE
Fix Objective C support (Swift 3 inference in Swift 4)

### ISSUE THREAD

**Issue by zrxq** [zvonicek/ImageSlideshow#194]
```
filename.m:910:47: Swift initializer 'ImageSource.init(image:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint
```

Since there are no explicit `@objc` attributes and Swift 4 compiler no longer agrees to silently infer them automatically, the library no longer compatible with Objective C apps. You either get the "inference deprecated" error, if you force the Swift 3 inference, or the "unknown selector", e.g.

```
filename.m:910:47: No visible @interface for 'ImageSource' declares the selector 'initWithImage:'
```

...if you don't.

**Comment by hyd00** [comment]
Same issue.. :(

**Comment by zvonicek** [comment]
I added @objcMembers annotations where possible so it should now generate those Objective-C interfaces. Check out the version 1.4.1.
