### ISSUE TITLE
Picture is shifted on iPhone X in landscape orientation

### ISSUE THREAD

**Issue by johnnyoin** [zvonicek/ImageSlideshow#200]
When running the example project on iPhone X simulator, turn it to landscape and tap the picture to go fullscreen.

The fullscreen image is shifted to the left.

**Comment by ElectroBuddha** [comment]
I can confirm, the imageslide is not centered on first rotation to landscape in fullscreen (only on iPhone X). After dragging the scrollview, image becomes centered again.

**Comment by Kam21** [comment]
I have the same issue as @ElectroBuddha .

imageslide is not centered on first rotation to landscape in fullscreen (only on iPhone X). After dragging the scrollview, image becomes centered again.

**Comment by zvonicek** [comment]
Hi guys, I confirm the bug, however, I haven't figured out yet how to fix it. It seems the frame is shifted on iPhone X for some reason. Will be glad for any help / PR solving the issue.

**Comment by scottcc** [comment]
I'm suspecting it has to do with the "notch" - does it shift in _both_ landscape orientations? I'd also look into whether constraints are using the newer "safe areas". Just my thoughts at the moment anyway.

**Comment by zvonicek** [comment]
I finally fixed the issue! It was enough to just set the `contentInsetAdjustmentBehavior` on scroll view to `.never`.
