### ISSUE TITLE
Using input sourcing with carthage

### ISSUE THREAD

**Issue by AntiVIRUZ** [zvonicek/ImageSlideshow#208]
I have not found a way to include a Kingfisher input source in build with Carthage instead of cocoapods. I can just copy it from source, but this is not the best way. Maybe it should be included by default? Or I don't know something

**Comment by zvonicek** [comment]
Yes, that's a known issue... I haven't really figured out how to create subspecs for different content providers like on CocoaPods. It's not possible to include it directly as that would cause compilation issues for some. 
So for now the only way is to copy it manually.
