### ISSUE TITLE
Can I use this library to view images based on their URL?

### ISSUE THREAD

**Issue by mazin933** [zvonicek/ImageSlideshow#212]
I have the images stored as URLs of type string. Is it possible to view them using this library?

I have tried the following (didn't work):

```
if let imageURL = URL(string: URLs[index]) {
                DispatchQueue.global().async {
                    let data = try? Data(contentsOf: imageURL)
                    if let data = data {
                        locationPhotoShow.setImageInputs(
                            ImageSource(image: UIImage(data: data))!
                        )
                    }
                }
                
            }
```

**Comment by kwstasna** [comment]
@mazin933 of course you can.

See the documentation here

https://github.com/zvonicek/ImageSlideshow#loading-images

I would suggest you using some caching library also for better user experience !

**Comment by scottcc** [comment]
FYI have had great results with KingFisher.
