### ISSUE TITLE
iOS 11 memory usage

### ISSUE THREAD

**Issue by georgehl** [zvonicek/ImageSlideshow#214]
Each of our reusable tableview cells have an imageslideshow. 
When scrolling, the memory jumps from 30mb to 160mb and cpu from 0 to 70%. The memory remains at 160mb even though we dequeue our tableview cells.
The only code we have for imageslideshow is setting the image inputs via SDWebImageSource.

We tried a device on iOS 10.3.3 and this issue doesn't occur. Devices we try on iOS 11 have this issue.

Any ideas?

**Comment by scottcc** [comment]
Are you sure you're not using strong references to self in the closures? Similar to #189?

**Comment by zvonicek** [comment]
Yes, I suppose it's related to #189. Please check you use weak references in `currentPageChanged`, `willBeginDragging` and `didEndDecelerating` closures.

**Comment by georgehl** [comment]
Sorry for the delay in responding. Thanks for getting back to me. We don't use currentPageChanged, willBeginDragging or didEndDecelerating. If I comment out the line `self.slideshow.setImageInputs(sdSource)` the memory issue doesn't happen. Is there something simple I'm not doing?

**Comment by Viktorfalkner** [comment]
I have the same problem as @georgehl, I don't use currentPageChanged, willBeginDragging or didEndDecelerating. 

            var inputs = [SDWebImageSource]()
            if let imageURLStrings = associatedProperty.imageURLStrings {
                for imageString in imageURLStrings {
                    let input = SDWebImageSource.init(urlString: imageString, placeholder: #imageLiteral(resourceName: "property-no-image"))
                    inputs.append(input!)
                }
            }
            slideShow.setImageInputs(inputs)

is all that is done, but when scrolling through a tableview it causes a memory leak and an eventual crash. Am I missing something as well?

**Comment by pratikgajbhiye222** [comment]
> I have the same problem as @georgehl, I don't use currentPageChanged, willBeginDragging or didEndDecelerating.
> 
> ```
>         var inputs = [SDWebImageSource]()
>         if let imageURLStrings = associatedProperty.imageURLStrings {
>             for imageString in imageURLStrings {
>                 let input = SDWebImageSource.init(urlString: imageString, placeholder: #imageLiteral(resourceName: "property-no-image"))
>                 inputs.append(input!)
>             }
>         }
>         slideShow.setImageInputs(inputs)
> ```
> 
> is all that is done, but when scrolling through a tableview it causes a memory leak and an eventual crash. Am I missing something as well?

Do U find anything?

**Comment by thepearl** [comment]
same problem .. this portion of code is consuming 1.7 Gb of RAM !!
```
func setupImagesSlider()
    {
        let pageIndicator = UIPageControl()
        pageIndicator.currentPageIndicatorTintColor = .defaultGreen
        pageIndicator.pageIndicatorTintColor = .lightGray
        
        imagesSlider.pageIndicator = pageIndicator
        
        guard
            let post = post,
            let photos = post.photo
        else { return }
        
        imagesSlider.pageIndicatorPosition = PageIndicatorPosition(horizontal: .center, vertical: .bottom)
        
        var imagesArray: [InputSource] = [InputSource]()
        
        for image in photos
        {
            if let _ = URL(string: image), let singleImage = AlamofireSource(urlString: image)
            {
                imagesArray.append(singleImage)
            }
            else
            {
                imagesArray.append(ImageSource(image: UIImage(named: "placeholder-image") ?? UIImage()))
            }
        }
```
