### ISSUE TITLE
AFURLSource placeholder not working

### ISSUE THREAD

**Issue by iSalah** [zvonicek/ImageSlideshow#215]
Hi,

The placeholder image doesn't seem to work with AFURLSource.
From the example app, if I set the slideshow image inputs with AFURLSource, the placeholder image won't show if the URL fails to load:

```
let placeholderImage = UIImage(named: "img1")!
let afNetworkingSource = [
    AFURLSource(urlString: "https://images.unsplash.com/photo-1432679963831-2dab49187847?w=1080", placeholder: placeholderImage)!,
    AFURLSource(urlString: "https://brokenurl", placeholder: placeholderImage)!,
    AFURLSource(urlString: "https://images.unsplash.com/photo-1463595373836-6e0b0a8ee322?w=1080", placeholder: placeholderImage)!
]

slideshow.setImageInputs(afNetworkingSource)

```

The second slide should show the placeholder image "img1", instead it shows a blank white slide.
When I click several times on this slide, I can see for a fraction of a second the placeholder image appears and disappears.

Can you figure this out ?
Thank you !

**Comment by zvonicek** [comment]
I've just merged your PR #218 so I'm closing the issue. Thank's for fixing it!
