### ISSUE TITLE
currentPageChanged is called too many times at auto scroll

### ISSUE THREAD

**Issue by johnnyoin** [zvonicek/ImageSlideshow#222]
When slideshow scrolls automatically (i.e. slideshowInterval > 0) currentPageChanged callback is called 3 times per slide. 
When running example, at first auto slide, console displays: 
```
current page: 1
current page: 0
current page: 1
```

This issue was introduced by 7083de0fc54b5729d5fa53f9b6f8a6edfb2c7796.

**Comment by zvonicek** [comment]
Thanks for the report, I fixed the issue.
