### ISSUE TITLE
[Crash] Division by zero

### ISSUE THREAD

**Issue by dogo** [zvonicek/ImageSlideshow#223]
Hi, @zvonicek 

I recently updated to ImageSlideshow 1.5.0 (using Carthage) from 1.4.1 and new crash has been introduced here:
<img width="1405" alt="screen shot 2018-01-22 at 23 46 29" src="https://user-images.githubusercontent.com/1487375/35253835-8f2a4346-ffce-11e7-8705-91588fcd645f.png">
<img width="1112" alt="screen shot 2018-01-22 at 23 46 40" src="https://user-images.githubusercontent.com/1487375/35253836-8f4fb4aa-ffce-11e7-9af6-f8bdb6de63d4.png">

The `scrollView.frame.size.width` is zero so the `primaryVisiblePage` division is by zero =(

**Comment by dogo** [comment]
@zvonicek , my bad was missing the `cancelLoad` method implementation.

**Comment by zvonicek** [comment]
Thanks for the report, I fixed that!
