### ISSUE TITLE
impossible to change position of closeButton

### ISSUE THREAD

**Issue by yulian948** [zvonicek/ImageSlideshow#226]
Starting from version 1.5 it's impossible to change position of close button. The reason is that now, close button frame is set in viewDidLayoutSubviews.

**Comment by zvonicek** [comment]
Oh, that's unfortunate. Can you think of a better solution that would keep it working but also work well with rotations on iPhone X (`safeAreaInsets`)?

**Comment by yulian948** [comment]
Wow, thanks for such a quick  @zvonicek,

I don't know if it will be a good approach, but we can add `closeButtonFrame` (or `closeButtonCenter`) open `CGRect` variable to `FullScreenSlideshowViewController`, so the users will be able to set it, and then `viewDidLayoutSubviews` will use that value.

**Comment by zvonicek** [comment]
Thanks @yulian948, that's probably the best solution. I added such property.
