### ISSUE TITLE
Could not to change background colour of Fullscreen view

### ISSUE THREAD

**Issue by timonchev** [zvonicek/ImageSlideshow#229]
Could not to change background colour of Fullscreen view. How to change it ?

tried like 

`open func didTap() {
        let fullScreenController = imageSlideShow.presentFullScreenController(from: self)
        fullScreenController.backgroundColor = .white

}`

2. And it possible use another images for fullscreen loading?

**Comment by zvonicek** [comment]
This should do the trick:

```
let fullScreenController = imageSlideShow.presentFullScreenController(from: self)
fullScreenController.view.backgroundColor = .white
```

You can use another images for fullscreen by configuring the `inputs` property on `FullScreenSlideshowViewController`.

**Comment by Neogene** [comment]
Doesn't seem to work solution proposed.

**Comment by Neogene** [comment]
`let fullScreenController = imageSlideShow.presentFullScreenController(from: self)
fullScreenController.view.backgroundColor = .white`

Is the only working solution, and using white hides the close button which uses a white icon, so after the code above I had to replace image of close button which a reversed one made in a photo editor.

`        fullScreenController.closeButton.setImage(UIImage(named: "ic_cross_black"), for: UIControlState())
`
