### ISSUE TITLE
pod installation issue 

### ISSUE THREAD

**Issue by invinciible** [zvonicek/ImageSlideshow#230]
<img width="545" alt="screen shot 2018-02-18 at 5 32 38 pm" src="https://user-images.githubusercontent.com/25017046/36351543-c88968a2-14d1-11e8-9680-56bc25f50e92.png">
<img width="547" alt="screen shot 2018-02-18 at 5 32 48 pm" src="https://user-images.githubusercontent.com/25017046/36351544-c8b3e1b8-14d1-11e8-93fb-ff16aa072efa.png">

**Comment by zvonicek** [comment]
I can think of two possible solutions, either remove `pod 'SDWebImage'` from `Podfile` since `ImageSlideshow/SDWebImage` will install it automatically. Or you can try `pod update`, the latest version of ImageSlideshow, 1.5.1, should be compatible with SDWebImage 4.
