### ISSUE TITLE
Can I Show a gif ?

### ISSUE THREAD

**Issue by farshadjahanmanesh** [zvonicek/ImageSlideshow#231]
hi, does ImageSlideshow support gif?

**Comment by zvonicek** [comment]
Hi, sorry, gifs are currently not supported.

**Comment by DanijelHuis** [comment]
Kingfisher supports gif without any extra effort. I've only briefly tried it but it seems to work:

`let kingfisherSource = [KingfisherSource(urlString: "https://images.unsplash.com/photo-1432679963831-2dab49187847?w=1080")!, KingfisherSource(urlString: "https://media.giphy.com/media/v6aOjy0Qo1fIA/giphy.gif")!, KingfisherSource(urlString: "https://images.unsplash.com/photo-1463595373836-6e0b0a8ee322?w=1080")!]`
