### ISSUE TITLE
Animation problem on orientation change

### ISSUE THREAD

**Issue by LouisBorlee** [zvonicek/ImageSlideshow#234]
Hi,

I'm having some animation troubles on orientation change after a scroll from the first to the last image (left swipe on the first image). The slideshow seems to be scrolling the whole bunch of my images.

Bug occurs on iPhone and iPad.

Thank you for your work, I appreciate it.

**Comment by zvonicek** [comment]
Hi! Thanks for reporting the issue. I managed to reproduce the problem by going to the first page, then scrolling back to the last page and rotating the screen. I'll look into this.

**Comment by zvonicek** [comment]
I finally managed to fix the problem, will release a new version soon.
