### ISSUE TITLE
PageControlPosition issue

### ISSUE THREAD

**Issue by oniikal3** [zvonicek/ImageSlideshow#240]
I need to set custom padding for page control but after I use
`slideshow.pageControlPosition = PageControlPosition.custom(padding: 90)`
page control doesn't move but bottom view constraint have been set to 90 instead of page control.

Is this bug?. Or I have to set something else?

**Comment by oniikal3** [comment]
@zvonicek As I debug and used set over. I saw it's call layoutPageControl() whenever layoutSubviews() has been call. So it will work only I set pageControlPosition to hidden for others it will reset to bottom by 
`        pageControl.frame = CGRect(x: 0, y: 0, width: frame.size.width, height: 10)
        pageControl.center = CGPoint(x: frame.size.width / 2, y: frame.size.height - pageControlBottomInset)`
this two line of your code.

**Comment by zvonicek** [comment]
Page indicator positioning improvements have been merged to master in #251.
