### ISSUE TITLE
Retain Cycle

### ISSUE THREAD

**Issue by piercifani** [zvonicek/ImageSlideshow#241]
There seems to be a retain cycle in ImageSlideshow between the `ZoomAnimatedTransitioningDelegate` and the slideshow itself

![](https://i.imgur.com/D1kiScR.jpg)

This leads to the items shown in the slideshow not being released, which leads to high memory pressure, which leads to crashes :)

**Comment by piercifani** [comment]
This patch seems to fix this issue https://github.com/Privalia/ImageSlideshow/commit/1441652756c75a4f4a4fcae17b6602934d267c66

**Comment by zvonicek** [comment]
Hi, thank you for reporting the bug and providing the patch. I'll release a new version with the fix today.

**Comment by zvonicek** [comment]
Your fix is now merged to master, thanks again!
