### ISSUE TITLE
Close button doesn't work

### ISSUE THREAD

**Issue by piercifani** [zvonicek/ImageSlideshow#242]
Seems that 1.5.2 broke the close button when the slideshow is presented fullscreen. Please see attached video for reproduction steps

![untitled](https://user-images.githubusercontent.com/869981/38862409-224c5012-4235-11e8-83a4-423e2d6038c9.gif)

**Comment by zvonicek** [comment]
Thanks for the report! I'm already aware of the bug and will fix it ASAP.
