### ISSUE TITLE
pod Parse Error

### ISSUE THREAD

**Issue by RishabhSRS** [zvonicek/ImageSlideshow#243]
getting trouble to install pods with pod 'ImageSlideshow/ParseSource'
<img width="572" alt="screen shot 2018-04-23 at 6 05 38 pm" src="https://user-images.githubusercontent.com/22503174/39126813-fc6594f8-4720-11e8-9b73-4b42671e3a9f.png">

**Comment by zvonicek** [comment]
Hi, did you try to call `pod repo update`?

**Comment by Tom-Fox1** [comment]
I have the same issue - I tried doing `pod repo update` and `pod install --repo-update` and still couldn't install it.

**Comment by Tom-Fox1** [comment]
Also `PFFile` needs to be changed to `PFFileObject`.

**Comment by zvonicek** [comment]
Hi @Tom-Fox1, I found out there was a mistake in Readme file, the correct command is `pod "ImageSlideshow/Parse"`.
