### ISSUE TITLE
currentPage not updated

### ISSUE THREAD

**Issue by adauguet** [zvonicek/ImageSlideshow#245]
When I try to replace current image inputs with new ones, the `currentPage` is not updated:
```swift
print(slideshow.currentPage) // 2
print(inputs.count) // 2
slideshow.setImageInputs(inputs)
print(slideshow.currentPage) // Still 2 here
slideshow.setCurrentPage(1)
print(slideshow.currentPage) // Still 2 here
```
The page control position is ok though.
Am I doing something wrong? Is it possible to change inputs?

**Comment by zvonicek** [comment]
Hi, this case should work properly. I cannot reproduce it, do you have an example project to share?
