### ISSUE TITLE
Add array list dyanmic 

### ISSUE THREAD

**Issue by vikasgupta4190** [zvonicek/ImageSlideshow#246]
i followed the documentation step by step and it's working perfectly

but i can only pass static images and here's my code :

slideShow.setImageInputs([AFURLSource(urlString: "https://mylink.com/image.jpg")!, AlamofireSource(urlString: "https://mylink.com/image2.jpg")!, AlamofireSource(urlString: "https://mylink.com/image3.jpg")!])

But i need to get the images url from JSON array dynamically and pass it to slideshow like that :

var jsonArray:NSarray = [String] 

slideShow.setImageInputs([jsonArray])
any idea how can i do that ?

**Comment by dickychan810** [comment]
var jsonArray = [InputSource]()

slideShow.setImageInputs(jsonArray)

I think it should be work

**Comment by vikasgupta4190** [comment]
thank you dear.
