### ISSUE TITLE
PageIndicator.swift and PageIndicatorPosition.swift missing in pod?

### ISSUE THREAD

**Issue by andrebng** [zvonicek/ImageSlideshow#252]
Is it possible that the both files mentioned in the title are missing in the pods? I am getting an error that models in those classes are missing actually saw that they were not included when I updated pods.

But maybe there is a problem on my end? I use version 1.6

**Comment by carloshmartins** [comment]
Hello Andre. Can you please upload an Image with the error? Thanks.

**Comment by andrebng** [comment]
I don't have the error anymore as I manually added the two files. I will close this issue for now. Thanks for the reply though :)
