### ISSUE TITLE
How to add images to the slider from an array of UIImage?

### ISSUE THREAD

**Issue by sujalshrestha** [zvonicek/ImageSlideshow#254]
We have to manually enter the images to add it in the slider. How can we add images from array of UIImage to the slider?

**Comment by RishabhSRS** [comment]
if you get it let me know it too , rishabh1450@gmail.com

**Comment by AlexGZC** [comment]
@sujalshrestha , Dude, did you get it?
I have the same question

**Comment by xhidnoda** [comment]
You can declare this var:
`var linksSource = [InputSource]()`

In my case i use this to add the arrays:
`linksSource.append(AFURLSource(urlString: link)!)`

And finally show images like this:
`imageSlideContainer.setImageInputs(linksSource)`
