### ISSUE TITLE
Image Selected

### ISSUE THREAD

**Issue by vaibhav-varshaaweblabs** [zvonicek/ImageSlideshow#256]
I want to perform different actions depending on the image in the SlideShow. How do I get the index of the image when I click?

**Comment by hsnbsst** [comment]
I wonder if I can answer that

**Comment by vaibhav-varshaaweblabs** [comment]
@hsnbsst I have created a Pull Request regarding this feature

**Comment by fernnando** [comment]
> @hsnbsst I have created a Pull Request regarding this feature

It's possible to access the image clicked using a gesture recognizer.

Example (Swift 4):

```
let gestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(didTap))
imageSlider.addGestureRecognizer(gestureRecognizer)

@objc func didTap(){
     //Here you can access the index using imageSlider.currentPage
}
```
