### ISSUE TITLE
work with KingFisher

### ISSUE THREAD

**Issue by omidrezaaa** [zvonicek/ImageSlideshow#259]
hi, first thanks for your library,
i cant work with slideshow library and kingfisher together, this is my code:

`let dsSlideShow = [KingfisherManager.shared.retrieveImage(with: URL(string: "http://myimageurl")! , options: nil, progressBlock: nil, completionHandler: {
            (image, error, cacheType, imageUrl) in
            if (error != nil){
                print("Error retrieving image!");
                return;
            }
            print("Download done!");
        })]
        slideShow.setImageInputs(dsSlideShow as! [InputSource])`

and when i run my project i get below error:

> ImageSlideshow was compiled with optimization - stepping may behave oddly; variables may not be available.

please help me and thanks in advance

**Comment by scottcc** [comment]
Hey @omidrezaaa - that's not an error. That's Xcode, and you're debugging with a breakpoint (or you halted/attached, whatever). Xcode is telling you that the compilation settings used won't allow you to step into the code for ImageSlideshow. This is not an issue with ImageSlideshow or Kingfisher - it's iOS programming (lots of resources on the web for you, google for "was compiled with optimization - stepping may behave oddly; variables may not be available."

**Comment by omidrezaaa** [comment]
Dear @scottcc first of all thanks for your reply,
but i check it is not related to issue that xcode response! i use Carthage and when i want to assign localimagesource to slideshow this error is returned, i'm new in xcode but i believe this is because something wrong in slideshow lib, maybe because they don't cover empty input source.
i think this error is related to load/ download image with kingfisher, i test it with other type of image source (use image in asset) it is work, but with kingfisher it doesn't.

could you help me?
thanks in advance

**Comment by zvonicek** [comment]
Thanks @scottcc for helping with this! You're right, this is not an issue of ImageSlideshow so I'm closing the ticket.

As for the possible causes, it may be that Carthage build does not actually include Kingfisher source – Carthage (unlike CocoaPods) does not support subspecs. We have therefore no way to check for Kingfisher (also Alamofire, etc.) dependency. You need to include KingfisherSource.swift manually in your project.
