### ISSUE TITLE
Pagecontrol overflow

### ISSUE THREAD

**Issue by kafejo** [zvonicek/ImageSlideshow#26]
If there are many images, the pagecontrol oveflows it's superview.

<img width="356" alt="screenshot 2016-04-05 09 03 25" src="https://cloud.githubusercontent.com/assets/4762172/14273781/5a3d21ca-fb0d-11e5-9421-0865382105d9.png">

Any idea how to solve that? (I mean UI solution)

**Comment by El-Fitz** [comment]
Maybe replacing the PageControl with some sort of label displaying the page number / total number of pages ?

**Comment by htarwara6245** [comment]
Working on it for displaying captions of pagecontrol (current/total) +1

**Comment by LukA888** [comment]
Any update for this? 😄

**Comment by scottcc** [comment]
+1 bump!

**Comment by zvonicek** [comment]
It's been a long time! But I can finally close this issue 🎉 

I've implemented a `PageIndicatorView` protocol in #251 that anyone can adopt to use their own page indicator. Also a numeric page indicator, `LabelPageIndicator`, showing just page numbers, is provided.
