### ISSUE TITLE
PageControl positioning

### ISSUE THREAD

**Issue by lendkazazi** [zvonicek/ImageSlideshow#261]
Hi,

i wanted to know if there is a way to change the positioning of the page indicator, i can see that there is  pagecontrol.center but it doesn't do anything.

Thanks,
Lend

**Comment by zvonicek** [comment]
Hi, check the [Page Indicator section](https://github.com/zvonicek/ImageSlideshow#page-indicator) in readme. You can use `pageIndicatorPosition` property for this.

**Comment by lendkazazi** [comment]
Use of unresolved identifier 'PageIndicatorPosition'

**Comment by zvonicek** [comment]
Update the framework.

**Comment by zvonicek** [comment]
^
https://github.com/zvonicek/ImageSlideshow/blob/master/ImageSlideshow/Classes/Core/PageIndicatorPosition.swift
