### ISSUE TITLE
ActivityIndicator hiding before image load

### ISSUE THREAD

**Issue by raeesmadathil** [zvonicek/ImageSlideshow#264]
I used DefaultActivityIndicator as loading spinner ,I found an issue , the activityindicator hiding/ stop animating even before image loaded, this issue found only after I updated to latest version, I kindly request to have a look on this issue

**Comment by zvonicek** [comment]
Hi, I was not able to reproduce the issue, could you send me any steps? The only problem I could reproduce was showing of activity indicator (#267).

**Comment by raeesmadathil** [comment]
Load some high quality (large file size) images from remote , the internet should not be with high speed, then you can see the issue what I explained above, the activity indicator suddenly disappear even before image is downloaded

**Comment by hilajqinnovation** [comment]
Hi Raees, how did you stop animating the activityIndicator? Because in my case I'm calling
self.slideshow.sd_showActivityIndicatorView() when loading the image. But even after loads the image, activityIndicator still animating.
