### ISSUE TITLE
Cannot convert [KingFisherSource] ??

### ISSUE THREAD

**Issue by khoozhiyan1997** [zvonicek/ImageSlideshow#265]
`      let kingfisherSource = [KingfisherSource(urlString: "https://images.unsplash.com/photo-1432679963831-2dab49187847?w=1080")!, KingfisherSource(urlString: "https://images.unsplash.com/photo-1447746249824-4be4e1b76d66?w=1080")!, KingfisherSource(urlString: "https://images.unsplash.com/photo-1463595373836-6e0b0a8ee322?w=1080")!]
          `

`      thumbnailImageView.setImageInputs(kingfisherSource)`
Cannot convert value of type '[KingfisherSource]' to expected argument type '[InputSource]'

How to solve this ? Thanks.

**Comment by arwenGhafur** [comment]
i have same issue how you fixed it?
