### ISSUE TITLE
is it possible to use the imageSlideShow in tableView or collectionView Cell?

### ISSUE THREAD

**Issue by farshadjahanmanesh** [zvonicek/ImageSlideshow#273]
i know that i can use it in these cells, but do we have any memory issues or something like that?

**Comment by zvonicek** [comment]
Hi, it should work, but I haven't really worked with this case yet. Be sure to enable image caching in the image loading library you use (eg. SDWebImage) since reusing of cells can result in repeated URL requests for same images.

**Comment by pratikgajbhiye222** [comment]
> Hi, it should work, but I haven't really worked with this case yet. Be sure to enable image caching in the image loading library you use (eg. SDWebImage) since reusing of cells can result in repeated URL requests for same images.

How to solve this problem?
