### ISSUE TITLE
'pageControlPosition' is deprecated: Use pageIndicatorPosition instead

### ISSUE THREAD

**Issue by AgungLaksana** [zvonicek/ImageSlideshow#286]
First of all, I wanna say thank you very much for this great library :)

I have a little bit issue in here, I get a warning

'pageControlPosition' is deprecated: Use pageIndicatorPosition instead

I get the error in here

```
open class FullScreenSlideshowViewController: UIViewController {

    open var slideshow: ImageSlideshow = {
        let slideshow = ImageSlideshow()
        slideshow.zoomEnabled = true
        slideshow.contentScaleMode = UIViewContentMode.scaleAspectFit
        slideshow.pageControlPosition = PageControlPosition.insideScrollView
        // turns off the timer
        slideshow.slideshowInterval = 0
        slideshow.autoresizingMask = [UIViewAutoresizing.flexibleWidth, UIViewAutoresizing.flexibleHeight]

        return slideshow
    }()

```

but when I change pageControlPosition to pageIndicatorPostion, it is said that pageIndicatorPostion doesn't have insideScrollView method

I am using  pod 'ImageSlideshow', '~> 1.6'

**Comment by vaibhav-varshaaweblabs** [comment]
Please use the latest pods
`pod 'ImageSlideshow'`

**Comment by gali8** [comment]
pod 'ImageSlideshow' not works.

**Comment by fbarraganef** [comment]
Same here I'm using the 1.7.0 version....

**Comment by zvonicek** [comment]
Hi! Yes, `pageControlPosition` is now deprecated and `pageIndicatorPosition` uses different enum cases. To achieve the same behaviour as with `insideScrollView` use `vertical: .bottom` position:

```swift
self.pageIndicatorPostion = PageIndicatorPosition(vertical: .bottom)
```

**Comment by syrakozz** [comment]
@zvonicek tx, but how i can hide it ? like .pageControlPosition = .hidden

**Comment by heisen273** [comment]
@syrakozz try .pageIndicatorPosition = .init()

**Comment by seenoevo** [comment]
@heisen273 this does not work
@zvonicek can you please implement functionality to hide page control indicator in conjunction with `pageIndicatorPosition`?
