### ISSUE TITLE
Style' is not a member type of 'UIActivityIndicatorView' Error

### ISSUE THREAD

**Issue by amsubhan** [zvonicek/ImageSlideshow#290]
I am getting these errors on installation of pod
![screen shot 2018-09-29 at 12 28 00 pm](https://user-images.githubusercontent.com/14370473/46242498-54a6a500-c3e3-11e8-97c3-7d86a61a31b3.png)

**Comment by muhammedm22** [comment]
Same issue in Xcode 9.4

**Comment by mobileapps23** [comment]
Got the same error at Xcode 9, and it's gone after updating to Xcode 10

**Comment by UPCRAP18** [comment]
The only thing you have to change is "UIActivityIndicatorView.Style" to "UIActivityIndicatorViewStyle"

**Comment by zvonicek** [comment]
I fixed this in master so it should now work in both Xcode 9 and Xcode 10 correctly.
