### ISSUE TITLE
Could not infer type for 'contentScaleMode'

### ISSUE THREAD

**Issue by chadbrochill317** [zvonicek/ImageSlideshow#292]
Hello I am getting the error posted in the title and below:
Could not infer type for 'contentScaleMode'

It is on line of code 173 on Slideshow.swift

open var contentScaleMode: UIView.ContentMode = UIView.ContentMode.scaleAspectFit {
        didSet {
            for view in slideshowItems {
                view.imageView.contentMode = contentScaleMode
            }
        }

Please help, I recently updated the pod.

**Comment by Ibolyaev** [comment]
I guess can be fixed like this:
`open var contentScaleMode: UIViewContentMode = .scaleAspectFit`
