### ISSUE TITLE
stop image loop

### ISSUE THREAD

**Issue by syrakozz** [zvonicek/ImageSlideshow#297]
hi how i can stop the image from looping per example 
we have 3 image : 
image 1 image 2 image 3  end

**Comment by zvonicek** [comment]
Hi, I'm not sure what you mean, but if you want to stop at specific image, you need to observe page changes and stop it manually by setting `slideshowInterval` to 0.

**Comment by Hassan143** [comment]
how i can stop images loop?

**Comment by syrakozz** [comment]
put cycle attribue to false
