### ISSUE TITLE
Bug after zoom out, image slide show not showing anything

### ISSUE THREAD

**Issue by syntax27** [zvonicek/ImageSlideshow#307]
hi, i need your help. When i trying to use your slideshow it works fine, but after i try to zoom it and close it, it cant load the image until i back to previous view. sry if my explanation is a bit not to detailed, i am still new in this platform

**Comment by spemat** [comment]
I'm experiencing the same issue.  It appears to be when zooming in and out only, as tapping on the close button itself is fine.  After using the zoom in and out, I close the full screen view and the image slides away and leaves a blank page without a method to go back to the previous View Controller.

Experienced on hardware and simulator (iPad 6th Gen).

**Comment by eduardojordan** [comment]
Me too , in simulator and device iPhone 7

**Comment by zvonicek** [comment]
I reworked the zoom out mechanism in db30f4c2ceb2639d091a4bf9f659bf821cdc4e45 so please check if the problem still appears. Feel free to reopen if it persists.
