### ISSUE TITLE
First zooming on detail

### ISSUE THREAD

**Issue by mstana** [zvonicek/ImageSlideshow#313]
Hello, 

when I set all images to source and present the slideShow the actual frame of UIImageView in slideShow is fullscreen. This cause error - when I am zooming in for the first time the actual photo is moving around a lot and is not centred in superview. 

When I zoom out and zoom in again the UIImageView frame is fixed and zooming is working as expected. 

here is small example: 
https://www.dropbox.com/s/qm83rf4dxlg6lkt/ScreenRecording_03-15-2019%2014-36-12.MP4?dl=0

**Comment by zvonicek** [comment]
Oh, hey @mstana :) ! Thanks for the bug report. Can you reproduce this in the example app? I can look into it soon if there's a repro on my side. Also, if you happen to know where the problem might be a PR is always welcomed. Take care!

**Comment by mstana** [comment]
Hey @zvonicek, I have replicated this problem also in example app. Steps to reprodude: 

1. Put external source (Alamofire, etc.) as input for `FullScreenSlideshowViewController`
2. Open `FullScreenSlideshowViewController`
3. Zoom in
4. When zoomed in scroll image up/down

I have also figured out the problem - when image is set async in load() method inside `ImageSlideshowItem` the layoutSubviews() for imageView size is not called which caused this issue. 

I have been testing the pod with `self?.layoutSubviews()` after the image is set and it fixed the problem.

**Comment by zvonicek** [comment]
I finally looked into it and found slightly better solution in d72264a53c034beab7d148fd7b4564a6c1945100 from #300 and I merged it 🎉 

Calling `self?.setNeedsLayout()` instead of `self?.layoutSubviews()` should have slightly better performance – layout subviews is called during the next layout update cycle.

Thanks for your help!
