### ISSUE TITLE
Dynamically changing height based on aspect ratio of image

### ISSUE THREAD

**Issue by ronakvora** [zvonicek/ImageSlideshow#315]
Is there any way to dynamically change the height of the ImageSlideshow view so that it takes into account the aspect ratio of the underlying images? Scale Aspect Fill just cuts the picture so that's no good for me, unfortunately, and Scale Aspect Fit leaves borders white.

**Comment by zvonicek** [comment]
Hi, this is unfortunately not supported and is probably not very straightforward to do. You always need to specify width and height yourself.
