### ISSUE TITLE
How to limit the dot indicator appear

### ISSUE THREAD

**Issue by lwirasatria99** [zvonicek/ImageSlideshow#317]
Can you make the dot indicator just show maybe to 4 or 5 dot, if we have much photo

Show all dot here

<img width="378" alt="Screen Shot 2019-03-31 at 11 54 56" src="https://user-images.githubusercontent.com/21220019/55284981-d46df600-53ab-11e9-865a-6cf8ef396722.png">

**Comment by alanrojas08** [comment]
Maybe you should try this

`imageSlideShow.pageIndicator = nil`

It will not appear anymore

**Comment by zvonicek** [comment]
Hi, this is unfortunately not supported on `UIPageControl`, but you can use label as a page indicator: `slideshow.pageIndicator = LabelPageIndicator(frame: .zero)`. Font and position are configurable.

Or you can implement your own page indicator by implemeting the protocol `PageIndicatorView`.

![Simulator Screen Shot - iPhone XR - 2019-04-14 at 12 19 55](https://user-images.githubusercontent.com/1540564/56091473-a14d5b80-5eaf-11e9-86ef-b0876973f704.png)

**Comment by lwirasatria99** [comment]
Thank you @zvonicek

**Comment by justdan0227** [comment]
Can we update the documentation to provide an example with the minimums of :

```
     imageSlideShow.pageIndicator = LabelPageIndicator(frame: .zero)
     imageSlideShow.pageIndicator?.numberOfPages = imageURLArray.count
```
