### ISSUE TITLE
Swift5

### ISSUE THREAD

**Issue by iNawaf** [zvonicek/ImageSlideshow#318]
Hi,

I updated my app to Swift5, and I'm using your awesome library.
I have Error right now says " Header 'ImageSlideshow-Swift.h' not found"
and another one says "Could not build Objective-C module 'ImageSlideshow'"

I hope you can update the library to support swift 5.

Regards,

**Comment by iamDiNGo** [comment]
@iNawaf I changed Deployment Target in framework to 10.0 and the error passed
