### ISSUE TITLE
Unable to set placeholder with AlamofireSource

### ISSUE THREAD

**Issue by christinachanhk** [zvonicek/ImageSlideshow#321]
I am using Using ImageSlideshow (1.7.0) with AlamofireSource. Although placeholder is set but only a white screen is shown when the url is not found (Error 404), the placeholder is not shown. AlamofireSource is created by following code: 

`let source = AlamofireSource(urlString: pic_url, placeholder: UIImage(named: image_default_photo))`

Found similar issue on https://github.com/zvonicek/ImageSlideshow/issues/309 , but adding `imageView.image = self.placeholder` to AlamofireSource "load" function in the first line does not help.

Thanks in advance.

**Comment by zvonicek** [comment]
Please reopen if you still see this happening!
