### ISSUE TITLE
Two warning after Kingfisher update and Swift 5

### ISSUE THREAD

**Issue by inawafalm** [zvonicek/ImageSlideshow#323]
Hey,

when I tried to use Result for Kingfisher's warning. and unwrap the second warning.
I get a bug that the indicator activity keeps showing even when the image already upload
. so it's like infinity indicator.

First warning released to kingfisher.
'setImage(with:placeholder:options:progressBlock:completionHandler:)' is deprecated: Use `Result` based callback instead.

Second warning: 
Expression implicitly coerced from 'UIFont?' to 'Any'

from this function:
  public override func sizeToFit() {
        let maximumString = String(repeating: "8", count: numberOfPages) as NSString
        self.frame.size = maximumString.size(withAttributes: [.font: font])
    }

Thanks

**Comment by dogo** [comment]
#326 fixes the warning related to Kingfisher

**Comment by zvonicek** [comment]
Should be fixed in the upcoming version. Thanks!
