### ISSUE TITLE
How can i use imagesource string array for setimageinputs

### ISSUE THREAD

**Issue by emresekeroglu** [zvonicek/ImageSlideshow#328]
Hi, thanks for this very nice library,
i have a json data and i get galleryurl array, but i can't use this array for slideShow.setImageInputs.

can you help me for this problem.

**Comment by zvonicek** [comment]
Hi, please read the documentation in readme. Use the appropriate supspec (eg `pod "ImageSlideshow/Alamofire"`) and corresponding input source (eg `AlamofireSource(urlString: "https://images.unsplash.com/photo-1432679963831-2dab49187847?w=1080")`).
