### ISSUE TITLE
Fullscreen image show again after dimiss.

### ISSUE THREAD

**Issue by sv9988** [zvonicek/ImageSlideshow#329]
When i use ImageSlideShow in uicollectionviewcell (the collectionview in uitableviewcell), It's no animation when dismiss and sometime fullscreen show again after dimisss by swipe.
So how can using ImageSlideShow in uicollectionviewcell inside uitableviewcell?
Thank you!

**Comment by zvonicek** [comment]
Hi, I made some changes to the dismiss mechanism in db30f4c2ceb2639d091a4bf9f659bf821cdc4e45 so it might fix the issue.
