### ISSUE TITLE
Sometimes crack app when tapping for full-screen! 

### ISSUE THREAD

**Issue by Kent-Mbn** [zvonicek/ImageSlideshow#334]
I see this issue when images from url loading. At that time, I tap to show full-screen, and I swipe to close. I see the app cracks! someone can tell me the reason and solutions for this.

**Comment by BossOz** [comment]
I think to have the same issue on iOs 13 
![issue](https://user-images.githubusercontent.com/4025510/64640836-20b56b80-d40b-11e9-91a9-e076669d5b00.gif)

**Comment by armandsavotins** [comment]
Same for iOS 13.

**Comment by andreycattalin** [comment]
#335

**Comment by dbake** [comment]
@andreycattalin I tried the solution, and am still getting the same behavior or the iPhone 8 and 11 in simulator.

**Comment by andreycattalin** [comment]
> @andreycattalin I tried the solution, and am still getting the same behavior or the iPhone 8 and 11 in simulator.

That is my Podfile if it can help you

`# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'clicktodrive' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for clicktodrive
  pod 'IQKeyboardManagerSwift', '~> 6.4'
  pod 'PanModal'
  pod 'Alamofire', '~> 4.9'
  pod 'AlamofireObjectMapper'
  # pod 'ImageSlideshow', '~> 1.8' disabled for iOS13 problem
  pod 'ImageSlideshow', :git => 'https://github.com/themobilecompany/ImageSlideshow.git', :branch => 'master'
  pod 'ImageSlideshow/Alamofire',  :git => 'https://github.com/themobilecompany/ImageSlideshow.git', :branch => 'master'
  
end
`

**Comment by andreycattalin** [comment]
Maybe you need to set modal presentation style:

 ```
let viewController:UIViewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "DemoViewController") as! DemoViewController
            viewController.modalPresentationStyle = .fullScreen
            self.present(viewController, animated: true, completion: nil)
```

**Comment by zvonicek** [comment]
The fix is in 19e448d536534e4d232b72ac59c012044d050b31! Sorry for the waiting.

**Comment by armandsavotins** [comment]
19e448d536534e4d232b72ac59c012044d050b31 fixes app to take fullscreen, but I have still some weird behaviour when full screen is being dismissed - kind a presenter is dismissed too.

**Comment by saitejapanditi67** [comment]
19e448d not working still getting the same issue 
Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan 333.5]'
