### ISSUE TITLE
insert Description

### ISSUE THREAD

**Issue by J-Arji** [zvonicek/ImageSlideshow#34]
how can insert description for every image ??

**Comment by JEKos** [comment]
+1

**Comment by kafejo** [comment]
+1

**Comment by zvonicek** [comment]
Thanks guys for the request! The possibility to add caption to images was not my priority, but I'll consider it for the next releases. Ideally, it should be highly configurable in terms of a position and alignment.

**Comment by zvonicek** [comment]
Closing this issue for now and will consider adding this feature later.
