### ISSUE TITLE
SwiftPM Support

### ISSUE THREAD

**Issue by michael-mckenna** [zvonicek/ImageSlideshow#340]
Hi,
  [SwiftPM](https://goo.gl/E01ufX) is Swift's official package manager.
  
  Here some articles about SwiftPM:
  
  * [An Introduction to the Swift Package Manager](https://goo.gl/byiOc6)
  * [Swift Dependency Management for iOS](https://goo.gl/7eaz1A)
  * [Getting Started with Swift Package Manager (SwiftPM)](https://goo.gl/rCHeQU)
  * [Swift.org: Package Manager](https://goo.gl/E01ufX)
  
  When your component is compatible with SwiftPM add on your `README.md` [![SwiftPM Compatible](https://camo.githubusercontent.com/52e3db230991dda10458295d71c859c34be466b6/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5377696674504d2d436f6d70617469626c652d627269676874677265656e2e737667)](https://goo.gl/E01ufX) badge on top and add a section for the installation with SwiftPM.

**Comment by techmehra** [comment]
Any Update on this

**Comment by pcmanik** [comment]
@zvonicek Anything new please?

**Comment by armintelker** [comment]
Any new updates

**Comment by christinachanhk** [comment]
Looking forward to this...

**Comment by zvonicek** [comment]
I just pushed the support for SPM to master!
