### ISSUE TITLE
Hide PageIndicator

### ISSUE THREAD

**Issue by syedrazackimran** [zvonicek/ImageSlideshow#349]
I would like to hide PageIndictor on FullScreenViewControll()

`
fullScreenController.slideshow.pageIndicator?.view.isHidden = true
`
i tried but getting failed result. kindly do needfully.

**Comment by Isvvc** [comment]
Instead of setting the view to hidden you can just set the `pageIndicator` itself to `nil`.

```Swift
fullScreenController.slideshow.pageIndicator = nil
```

**Comment by zvonicek** [comment]
Isaac is right, thanks for the help!
