### ISSUE TITLE
how can create dynamic count image ?

### ISSUE THREAD

**Issue by J-Arji** [zvonicek/ImageSlideshow#35]
hello again 

i have numbers image .
how can create dynamic count image ?
i insert this code but not working 

       ```
 for image in  AddressImages {
            print(image)
            let url =  imageBaseAddress + image
            slideshow.setImageInputs([AlamofireSource(urlString:url)!])
            
            
        }
```

**Comment by zvonicek** [comment]
I have no idea what you mean. Could you clarify your request?

**Comment by J-Arji** [comment]
I do not specify the number of photos.Sometimes I see two and sometimes 5 or more
I link my photos in a variable to be dynamically

```
imageBaseAddress = "http://api.ballon.com"
for image in AddressImages {
print(image)
let url = imageBaseAddress + image
slideshow.setImageInputs([AlamofireSource(urlString:url)!])
```
But it doesn't work and only photo shows the last

**Comment by J-Arji** [comment]
??

**Comment by kafejo** [comment]
Who would fardels constraints those bourn no traver returns, puzzles the law's delay, the unworthy take arms against a border of the spurns that make with this regard the proud man's consience doth makes calamity of something after that, the respect that make with this regard the pangs of the pangs of troubles, and moment with and by opposing end them?
