### ISSUE TITLE
Not working in iOS 13

### ISSUE THREAD

**Issue by kanagudurai** [zvonicek/ImageSlideshow#350]

**Comment by pauloec** [comment]
Has anyone figured out this?

**Comment by gowtham171** [comment]
in imageSlideShow.swift add the below code inside PresentFullScreenController function
"fullscreen.modalPresentationStyle = .fullScreen"

**Comment by ajswanny** [comment]
That didn't work for me. Tapping "X" still results in a black screen. Is there anything else you did, @gowtham171, aside from that?

**Comment by vladaverin24** [comment]
I think [this](https://developer.apple.com/documentation/uikit/uiviewcontroller/3229894-ismodalinpresentation) is what we're looking for:
```
if #available(iOS 13.0, *) {
    fullscreen.modalPresentationStyle = .fullScreen
    fullscreen.isModalInPresentation = true
}
```

**Comment by KyleTweak** [comment]
@vladaverin24 Works great, thank you!

**Comment by zvonicek** [comment]
The fix is in 19e448d536534e4d232b72ac59c012044d050b31! Sorry for the waiting.

**Comment by tadeha** [comment]
After dismissing, it shows a blank, black screen for me.

**Comment by zvonicek** [comment]
Can you reproduce this in the example project? I'm having problems with reproducing the issue on my side.

**Comment by cagdaseksi** [comment]
> After dismissing, it shows a blank, black screen for me.

I have the same problem. How did you solve the problem?

**Comment by cagdaseksi** [comment]
> > After dismissing, it shows a blank, black screen for me.
> 
> I have the same problem. How did you solve the problem?

Works great, thank you!
