### ISSUE TITLE
ImageSlideshow/Alamofire doesn't work

### ISSUE THREAD

**Issue by VahidGR** [zvonicek/ImageSlideshow#358]
I have used Alamofire library to load images before but after updating to Xcode 11 it did not work. So I moved on to Kingfisher library.

You can look into it if you get the chance

**Comment by nvelichkin** [comment]
I had same problem. It comes with iOS 13. Add this in AppDelegate, for example. This should fix it. DataRequest is public class from Alamofire.
 `DataRequest.addAcceptableImageContentTypes(["application/octet-stream"])`

**Comment by raghad54** [comment]
pod Don't compatible with pod "ImageSlideshow/Alamofire"
return 
 ImageSlideshow/Alamofire was resolved to 1.8.3, which depends on
      AlamofireImage (~> 3.0) was resolved to 3.1.0, which depends on
        Alamofire (~> 4.0)
