### ISSUE TITLE
Every slideshow image to different view controller. Is it possible?

### ISSUE THREAD

**Issue by JEKos** [zvonicek/ImageSlideshow#36]
Hi,
Is it possible for example, when you tap the 1st image from slideshow to go to a view controller, when you tap the 2nd image go to different view controller or tableview etc. ???
Is it possible, if yes, then how? Can you give me a simple example with that, how to make to recognize each image as a different thing in slideshow?

**Comment by zvonicek** [comment]
Hi. The library contains just a plain image slideshow, so it's up to you how you'll manage your navigation. The best way to implement such functionality is to add a custom gesture recognizer to each `ImageSlideshowItem` stored in `slideshowItems` property.

**Comment by JEKos** [comment]
Can you please give an example for that you suggest as the best solution?

**Comment by nazrdogan** [comment]
+1
