### ISSUE TITLE
Close button is not visible when SPM is used

### ISSUE THREAD

**Issue by pcmanik** [zvonicek/ImageSlideshow#362]
SPM does not support binary attachments, so cross mark for closing slideshow is not visible. Can you please replace it with custom one rendered using CoreGraphics?

https://github.com/zvonicek/ImageSlideshow/blob/master/ImageSlideshow/Assets/ic_cross_white%403x.png

**Comment by Isvvc** [comment]
The SF Symbol `xmark` could be a really easy solution to this.

**Comment by Isvvc** [comment]
In fact, here's a workaround until this can get fixed:

In whatever function you're using to call `presentFullScreenController`, you can modify the button of the resulting full-screen slideshow.

```Swift
let fullscreenSlideshow = slideshow.presentFullScreenController(from: self)
fullscreenSlideshow?.closeButton.setImage(UIImage(systemName: "xmark"), for: UIControl.State())
fullscreenSlideshow?.closeButton.tintColor = .white
```
