### ISSUE TITLE
Incompatible Dependency for Swift Package

### ISSUE THREAD

**Issue by neodave** [zvonicek/ImageSlideshow#363]
Hello, I am getting the title error message when trying to add this as a Swift Package. It is saying that th AlamofireImage framework is the issue. After some googling I think it might be that you are calling a branch rather than a version. But not sure. Have you seen this error before?

 .package(url: "https://github.com/Alamofire/AlamofireImage.git", .branch("master"))

**Comment by andrewreeman** [comment]
What is the exact error message? 

Is it related to this issue I've just opened: #371
It looks like the latest AlamofireImage is not supported by ImageSlideshow until issue 371 is resolved

**Comment by zvonicek** [comment]
I updated the dependency version in 3b11e03cafff2ed8120e66e7edd3a13685bbb37b, hope it will help. Please reopen the ticket if you experience any further issues.
