### ISSUE TITLE
Not able to swipe to dismiss

### ISSUE THREAD

**Issue by DhavalBhimani** [zvonicek/ImageSlideshow#365]
I am not able to swipe image to dismiss. this happens only with some specific image. for other images it works.

This image do not work swipe to dismiss : SDWebImageSource(urlString: "https://images.unsplash.com/photo-1447746249824-4be4e1b76d66?w=1080")!

**Comment by zvonicek** [comment]
Hi, I'm sorry but I can't reproduce it on my side. Please share more details with me with your setup – OS version, device type and example code on which the problem happens. Feel free to reopen the ticket then.
