### ISSUE TITLE
Crash after exit from fullscreen

### ISSUE THREAD

**Issue by maley63** [zvonicek/ImageSlideshow#366]
Hi there.
When the image is in fullscreen mode and I try to exit fullscreen.  The App crashes and goes back to Root View (LoginPage).
Has this happened to anyone else?

I am running a separate app and it works fine.  My code is following the instructions.

Can anyone help?

Also can anyone think of a way to stop viewDidAppear/Disappear being called when I enter/exit fullscreen mode?

Thanks

**Comment by armandsavotins** [comment]
Same on iOS 13. It looks like this problem not present on earlier iOS versions.

**Comment by zkon** [comment]
Hi @maley63 , did you get anywhere with this - it happens on my app also. I just wondering if there is an alternative.

Thanks.

**Comment by maley63** [comment]
I managed to sort it out.  

It was due to the navigation controller and my initial view controller.

I would have a look at where you embed your nav contr and say thats the initial VC.  See if that helps.

**Comment by zkon** [comment]
Hi @maley63, thanks for your reply. My swift is a bit rusty as I've been on android for over a year. The app is using a split view controller with table view controller and detail view controller. The detail view initiatives the full screen view: `xxx.presentFullScreenController(from: self)` 

When shown it is not shown in full screen view:
![image](https://user-images.githubusercontent.com/1008020/75951615-9739ae80-5f00-11ea-83f9-23609baf6acd.png)

When you hit the X it briefly flashes up the previous view then just goes black - doesn't actually crash. I'm not sure what's going on nor how to find out where it's at. It only started happening when iOS 13 came out.

**Comment by diegoalex** [comment]
This fix for me:
https://github.com/zvonicek/ImageSlideshow/issues/354#issuecomment-541632991

**Comment by zvonicek** [comment]
Should be fixed in version 1.9.0. Let me know if it works properly now and reopen the ticket if not.
