### ISSUE TITLE
Update AlamofireImage support

### ISSUE THREAD

**Issue by andrewreeman** [zvonicek/ImageSlideshow#371]
The current support for AlamofireImage is for version 3. 
This should update to version 4 which also supports version 5 of Alamofire. 

Migration guide on AlamofireImage can be found here:
[Migration to AlamofireImage 4.0](https://github.com/Alamofire/AlamofireImage/blob/master/Documentation/AlamofireImage%204.0%20Migration%20Guide.md)

**Comment by zvonicek** [comment]
Fixed in 234d430fb32e89fb84c845f0f4d3711ab8608c53
