### ISSUE TITLE
Page Control below Images

### ISSUE THREAD

**Issue by ShehanMadushanka** [zvonicek/ImageSlideshow#374]
I want to create a view like this. But there is a limitation in page control positioning. I want page control below the image border. 

<img width="380" alt="Screenshot 2020-03-03 at 16 20 37" src="https://user-images.githubusercontent.com/25446951/75768819-1bf2c400-5d6b-11ea-87e3-5de146647ce2.png">

**Comment by Unknoob** [comment]
You can do it by using the `pageIndicatorPosition`.

```
imageSlideshow.pageIndicatorPosition = PageIndicatorPosition(horizontal: .center, vertical: .under)
```

Or if you need a specific distance from the page control you can use
```
.pageIndicatorPosition = PageIndicatorPosition(horizontal: .center, vertical: .customUnder(padding: pageControlDistance))
```
