### ISSUE TITLE
Full screen dismiss error 

### ISSUE THREAD

**Issue by AnHoncharenko** [zvonicek/ImageSlideshow#378]
after dismiss, pressing the screen does not work
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/45729211/78260930-3b664380-7507-11ea-8f86-f062ddf75b25.gif)

**Comment by AnimatorJoe** [comment]
I encountered this error as well where I had a view controller which has an ImageSlideShow in it being presented on top of another view controller.

``
detailPage = DetailedEntryViewController() // this vc has an ImageSlideShow subview
self.present(detailPage, animated: true)
``

I'm not sure why it breaks, but a temporary fix I found is to make sure the presented view controller is set to take up the entire screen using `detailPage.modalPresentationStyle = .fullScreen`.

Hope that helps.

**Comment by AnimatorJoe** [comment]
A better solution would probably be [this](https://github.com/zvonicek/ImageSlideshow/issues/354).

**Comment by fbarraganef** [comment]
same here, I have the same problem. I already tried with the modalpresentation but not work.

**Comment by gang018** [comment]
> I encountered this error as well where I had a view controller which has an ImageSlideShow in it being presented on top of another view controller.
> 
> ```
> detailPage = DetailedEntryViewController() // this vc has an ImageSlideShow subview
> self.present(detailPage, animated: true)
> ```
> 
> I'm not sure why it breaks, but a temporary fix I found is to make sure the presented view controller is set to take up the entire screen using `detailPage.modalPresentationStyle = .fullScreen`.
> 
> Hope that helps.

Thanks a lot, your solution helped me! :)

**Comment by AnHoncharenko** [comment]
My solution 
in viewDidLoad {
let gestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(didTapServiceImage))
        serviceImagesSlides.addGestureRecognizer(gestureRecognizer)
}

then 
 @objc func didTapServiceImage() {
        let imagesViewController = FullScreenSlideshowViewController()
        imagesViewController.inputs = inputsImage
        imagesViewController.initialPage = serviceImagesSlides.currentPage
        imagesViewController.pageSelected = { self.serviceImagesSlides.setCurrentPage($0, animated: true) }
        self.present(imagesViewController, animated: true, completion: nil)
    }
one problem: you cannot close the screen with a gesture down

**Comment by AnHoncharenko** [comment]
M solution that supports dismiss up and down on a swipe

class ServiceImageFullScreenViewController: FullScreenSlideshowViewController {
    var panGestureRecognizer: UIPanGestureRecognizer?
    var viewTranslation = CGPoint(x: 0, y: 0)

    override func viewDidLoad() {
        super.viewDidLoad()
        panGestureRecognizer = UIPanGestureRecognizer(target: self, action: #selector(panGestureAction))
        view.addGestureRecognizer(panGestureRecognizer!)
        closeButton.setImage(UIImage(named: "close"), for: .normal)
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
    }

    @objc func panGestureAction(recognizer: UIPanGestureRecognizer) {
        switch recognizer.state {
        case .changed:
            viewTranslation = recognizer.translation(in: view)
            UIView.animate(withDuration: 0.5, delay: 0, usingSpringWithDamping: 0.7, initialSpringVelocity: 1, options: .curveEaseOut, animations: {
                self.view.transform = CGAffineTransform(translationX: 0, y: self.viewTranslation.y)
            })

        case .ended:
            if viewTranslation.y < -200 {
                dismiss(animated: true, completion: nil)
            }
            if viewTranslation.y < 200 {
                UIView.animate(withDuration: 0.5, delay: 0, usingSpringWithDamping: 0.7, initialSpringVelocity: 1, options: .curveEaseOut, animations: {
                    self.view.transform = .identity
                })
            } else {
                dismiss(animated: true, completion: nil)
            }

        default:
            break
        }
    }
}

example
 let imageViewController = ServiceImageFullScreenViewController()
                imageViewController.modalPresentationStyle = .overCurrentContext                imageViewController.inputs = self.inputImages
                self.present(imageViewController, animated: true, completion: nil)

**Comment by iSashaCH** [comment]
just confirming this issue still persists. When fullscreen is presented from the formSheet controller that contains ImageSlideshow - after dismissal of the fullscreen presenting controller does not reappear on the screen. It still works on foreground but does no rendering.

**Comment by zvonicek** [comment]
Thanks for reporting this! I can reproduce it on my side, but don't know what the fix could be now. The simple fix is to disable custom `ZoomAnimatedTransitioning`, as the custom zoom out animation (class `ZoomOutAnimator`) is what's causing the problem.

I've found references to this problem elsewhere on the internet, so it seems like it could be an iOS 13 bug. If anyone knows a fix or workaround please open a PR!

**Comment by zvonicek** [comment]
I think I found a solution in db30f4c2ceb2639d091a4bf9f659bf821cdc4e45. Please give it a try, it should now work properly.

**Comment by zvonicek** [comment]
Should be fixed in version 1.9.0. Let me know if it works properly now and reopen the ticket if not.

**Comment by iSashaCH** [comment]
Confirm. It works ok now. Thank you for a quick response.
