### ISSUE TITLE
How to make status bar appear when show image

### ISSUE THREAD

**Issue by dacvinhng** [zvonicek/ImageSlideshow#379]
Hi,
When we select a item, it will zoom to full screen view that show image and we can not see status bar of phone (where contain time and battery)
How to make status bar appear when show image?
Thanks

**Comment by zvonicek** [comment]
Hi, you would need to subclass `FullScreenSlideshowViewController` with

```
    override open var prefersStatusBarHidden: Bool {
        return false
    }
```

and then present your sublass manually yourself.
