### ISSUE TITLE
SPM fails to resolve dependencies

### ISSUE THREAD

**Issue by CocoaPriest** [zvonicek/ImageSlideshow#384]
When trying to add ImageSlideshow with SPM:

> because no versions of ImageSlideshow match the requirement 1.8.4..<2.0.0 and package imageslideshow is required using a version-based requirement and it depends on unversion package alamofireimage, ImageSlideshow >=1.8.3 is forbidden.
> And because root depends on ImageSlideshow 1.8.3..<2.0.0, version solving failed.

Looks like alamofireimage's version wasn't specified?

**Comment by Isvvc** [comment]
A workaround for this is to select `master` branch instead of choosing a version.

**Comment by zvonicek** [comment]
I made a new release so this should now be fixed.
