### ISSUE TITLE
Insert more images after going fullscreen (ActivityLoader while images load)

### ISSUE THREAD

**Issue by Bhavik-P** [zvonicek/ImageSlideshow#41]
Is there a way to add more images after it is in fullscreen
sample case:
there are 10 albums; covers of each shown on collectionviewcell. If user taps on collectioncell, ImageSlideshow opens in full screen. How can I popup the full screen, make a call to get all the images in that album then load it within ImageSlideshow?

I figured one way of doing is by 

```
albumManager.fetchAllImages( completion: {
      result in
      var imageSource = [ImageSource]()
      for image in result!{
            imageSource.append(ImageSource(image: image))
       }
       userImagesView.setImageInputs(imageSource)
       fsvc.pageSelected = {(page: Int) in
          imagesSlideshow.setScrollViewPage(page, animated: false)
       }
       fsvc.initialImageIndex =  imagesSlideshow.scrollViewPage
       fsvc.inputs =  imagesSlideshow.images
       self.transitionDelegate = ZoomAnimatedTransitioningDelegate(slideshowView:  imagesSlideshow, slideshowController: fsvc)
       fsvc.transitioningDelegate = self.transitionDelegate
       self.presentViewController(fsvc, animated: true, completion: nil)
 })
```

The only issue with this code is that if a user taps on a cell, it takes some time before showing the ImageSlideshow in fullscreen (obviously because it makes a network call to download all the images)

Is there a simpler way to do this? 
I was hoping to also add an activity loader while the pictures download.

**Comment by zvonicek** [comment]
Sorry for getting so late to this. There should be no problem with initializing fullscreen slideshow with more images then in parent slideshow. 

As for the delay, when loading images from URL (e.g. using Alamofire) there should be none as it's all done asynchronously. As for the initialization directly from UIImage, this can take some time. However, UIImage is thread safe on newer iOS versions so I could probably do image initialization on background thread. I'll look into this.

**Comment by layanavg** [comment]
Hi @zvonicek ,
I need to show an activity indicator in full screen mode while loading images from URL. Currently it is showing blank black screen. Please help .......
