### ISSUE TITLE
Init over 30 images get memory warning and crash app

### ISSUE THREAD

**Issue by mrmilng** [zvonicek/ImageSlideshow#42]
I input over 30 images then my apps easy to crash cause of memory warning. 
Is there a way to lazy load the previous and right after images from current page not all images at the time.

**Comment by luaNewer** [comment]
@zvonicek @kafejo @mrmilng 
I found some similar problem，so I doubt is there some resource allocation fault in your code？

**Comment by zvonicek** [comment]
Hi, thanks for the report! This really is a problem, happening when you try to load bigger number of images. It is an impact of loading all images eagerly when input sources are set. 

I'd like to implement lazy loading so images are actually loaded only when (or short time before) needed and freed when not needed. This should solve this problem.

**Comment by luaNewer** [comment]
@zvonicek 
Thanks for reply! I also found that more setImageInputs was called, more memory was consumed. Hoping for your 1.0 Release!

**Comment by zvonicek** [comment]
Hi! I've just released v`1.0.0-beta.1` with lazy loading implemented. You can now use the `preload` property to configure image preloading. Please check that and let me know if it solves your problem.
