### ISSUE TITLE
SDWebImage cache

### ISSUE THREAD

**Issue by NikKovV** [zvonicek/ImageSlideshow#43]
Hello! Will you implement support for SDWebImage?

**Comment by NikKovV** [comment]
I created a class with code:

```
@objc public class SDWebImageSource: NSObject, InputSource {
    var url: NSURL!
    
    public init(url: NSURL) {
        self.url = url
        super.init()
    }
    
    public init?(urlString: String) {
        if let validUrl = NSURL(string: urlString) {
            self.url = validUrl
            super.init()
        } else {
            super.init()
            return nil
        }
    }
    
    public func setToImageView(imageView: UIImageView) {
        imageView.sd_setImageWithURL(self.url)
    }
}
```
than i getting and array of urls:
```
...
        for (NSString *path in detailNewsImagePaths)
        {
            SDWebImageSource *sdSource = [[SDWebImageSource alloc]initWithUrl:[[ApiConnection sharedInstance]urlFromRelativePath:path]];
            [self.imagesArray addObject:sdSource];
        }
    [cell.detailNewsBigImagePager setImageInputs:self.imagesArray];
```
but i taking an error
**NSArray element failed to match the Swift Array Element type**

![2016-07-06 15 40 52](https://cloud.githubusercontent.com/assets/16647690/16618083/72d6427e-4398-11e6-9bb9-e675703959fd.png)

help please)

**Comment by littner** [comment]
Using sdwebimage and your class, I ended up doing it like:

Initialize empty array:
`var sd_images: [SDWebImageSource] = []`

Interate trough "images" (those are just http links to images)
          ```
      for image in images {
                    sd_images.append(SDWebImageSource(url: NSURL(string: image)!))
                }
```
Set the source
` self.poster.setImageInputs(sd_images)`

**Comment by NikKovV** [comment]
But i have code in OBJ-C, so i can't add to my code var sd_images: [SDWebImageSource] = []
=(

**Comment by littner** [comment]
Try doing 

`if let last = images[images.count - 1]`

**Comment by NikKovV** [comment]
Sorry, i cant figure out where should i do this. Please, give a full code.

**Comment by littner** [comment]
Tell what actually you need. Is there problem in 
```
if let last = images.last {
}
```

Or there something else?

**Comment by littner** [comment]
Because, if you stuck only with this, then replace 
```
if let last = images.last {
// stuff
}

```
with

```
if let last = images[images.count - 1] {
//stuff
}
```

**Comment by NikKovV** [comment]
The problem in somewhere else. I think that NSArray not recognized as Swift array with protocol <InputSource> for some reasons. I've created a pull request, please check it and merge if everything ok! ;) #47

**Comment by zvonicek** [comment]
The pull request was merged, you can now use SDWebImage with `SDWebImage` subspec (similarly as AFNetworking or Alamofire).

Thanks for your contribution!

**Comment by NikKovV** [comment]
When i try to download pod ("ImageSlideshow/SDWebImage") it throws:

![2016-07-18 10 44 38](https://cloud.githubusercontent.com/assets/16647690/16909537/84d9b9ba-4ce4-11e6-975c-31d4d10debef.png)

I think you should update version and readme.

**Comment by zvonicek** [comment]
Hi @NikKovV, yes, it's not released on CocoaPods yet. In the meanwhile, you can point your Podfile directly to this repository.

```pod 'ImageSlideshow/SDWebImage', :git => 'https://github.com/zvonicek/ImageSlideshow.git'```

**Comment by NikKovV** [comment]
You really shouldn't use SDWebImage (~> 3.8) yet, becouse most of libraries works with 3.7.x
I have to fork your project and change podspec due to use it though.

**Comment by zvonicek** [comment]
I see! I was not aware of this issue. So I'll lower the dependency to earliest compatible version.
