### ISSUE TITLE
Readme fix

### ISSUE THREAD

**Issue by littner** [zvonicek/ImageSlideshow#44]
In readme file you have following code
```
// set the initial page
  ctr.initialPage = slideshow.scrollViewPage
```

In _FullScreenSlideshowViewController_ class there is another variable **initialImageIndex**

**Comment by zvonicek** [comment]
Thank you for catching this and sorry for inconsistency in the readme. The correct variant is this:

```
ctr.initialImageIndex = slideshow.scrollViewPage
``` 

I fixed this in readme.
