### ISSUE TITLE
Parse image files

### ISSUE THREAD

**Issue by kwstasna** [zvonicek/ImageSlideshow#45]
Hello. There is a wierd situation here.
I'm making an app in iOS and the same app with Android we share a database at Parse.com
So when i use your library (which is awesome btw!!)
i fetch some images and this is the code

```
private var almo   = [AlamofireSource]()
var sliderPinakas = [AnyObject]()

override func viewDidLoad() {
        super.viewDidLoad()
slider.backgroundColor = UIColor.whiteColor()
    slider.slideshowInterval = 5.0
    slider.pageControlPosition = PageControlPosition.UnderScrollView
    slider.pageControl.currentPageIndicatorTintColor = UIColor.lightGrayColor();
    slider.pageControl.pageIndicatorTintColor = UIColor.blackColor();
 let idaki = recipeObj.objectId
    let pointer2 = PFObject(outDataWithClassName:"Recipes", objectId: idaki!)
     let galquery = PFQuery(className:"sliderRecipes")
        galquery.whereKey("recipe", equalTo: pointer2)
    galquery.findObjectsInBackgroundWithBlock {
        (objects: [PFObject]?, error: NSError?) -> Void in
 if error == nil {
            // The find succeeded.
            print("Successfully retrieved \(objects!.count) scores.")
            // Do something with the found objects
            if let objects = objects {
                for object in objects {
                   let glrimg = object["sliderImage"] as! PFFile
                    
                   self.sliderPinakas.append(glrimg.url!)
                    
                }
               print(self.sliderPinakas)
                for image in  self.sliderPinakas {
                    let url =  image
                    self.almo.append(AlamofireSource(urlString:url as! String)!)
                }
                self.slider.setImageInputs(self.almo)
                print(self.almo)
                
            }
        } else {
            // Log details of the failure
            print("Error: \(error!) \(error!.userInfo)")
        } 
    }
}
```

So when i upload images on Parse from Android
and i check out from iOS it doesnt show the image via url link but it makes the views for as many as the images are....
 if i make it as an UIImage i can see it normally.
Maybe you should check it out!

P.S. when i upload from the parse dashboard from my Mac i can also see it normally.

**Comment by NikKovV** [comment]
@kwstasna maybe you need to send authorization http header to download image?

**Comment by kwstasna** [comment]
@NikKovV so why when i load images that i have uploaded from my iphone, it shows them...
and when i load images uploaded from android phone it doesnt show them at all?

**Comment by zvonicek** [comment]
Hmm, this sounds to rather be related to Parse or Alamofire at worst, but not ImageSlideshow. Please check if it works with ordinary UIImageView. 

I'm closing the issue, but if you give me more guidance to reliably reproduce the issue, I'll reopen it.

**Comment by pratikgajbhiye222** [comment]
> @NikKovV so why when i load images that i have uploaded from my iphone, it shows them...
> and when i load images uploaded from android phone it doesnt show them at all?

Hey ,I am taking about this , check the latest issue posted by me , I need help

**Comment by pratikgajbhiye222** [comment]
> Hello. There is a wierd situation here.
> I'm making an app in iOS and the same app with Android we share a database at Parse.com
> So when i use your library (which is awesome btw!!)
> i fetch some images and this is the code
> 
> ```
> private var almo   = [AlamofireSource]()
> var sliderPinakas = [AnyObject]()
> 
> override func viewDidLoad() {
>         super.viewDidLoad()
> slider.backgroundColor = UIColor.whiteColor()
>     slider.slideshowInterval = 5.0
>     slider.pageControlPosition = PageControlPosition.UnderScrollView
>     slider.pageControl.currentPageIndicatorTintColor = UIColor.lightGrayColor();
>     slider.pageControl.pageIndicatorTintColor = UIColor.blackColor();
>  let idaki = recipeObj.objectId
>     let pointer2 = PFObject(outDataWithClassName:"Recipes", objectId: idaki!)
>      let galquery = PFQuery(className:"sliderRecipes")
>         galquery.whereKey("recipe", equalTo: pointer2)
>     galquery.findObjectsInBackgroundWithBlock {
>         (objects: [PFObject]?, error: NSError?) -> Void in
>  if error == nil {
>             // The find succeeded.
>             print("Successfully retrieved \(objects!.count) scores.")
>             // Do something with the found objects
>             if let objects = objects {
>                 for object in objects {
>                    let glrimg = object["sliderImage"] as! PFFile
> 
>                    self.sliderPinakas.append(glrimg.url!)
> 
>                 }
>                print(self.sliderPinakas)
>                 for image in  self.sliderPinakas {
>                     let url =  image
>                     self.almo.append(AlamofireSource(urlString:url as! String)!)
>                 }
>                 self.slider.setImageInputs(self.almo)
>                 print(self.almo)
> 
>             }
>         } else {
>             // Log details of the failure
>             print("Error: \(error!) \(error!.userInfo)")
>         } 
>     }
> }
> ```
> 
> So when i upload images on Parse from Android
> and i check out from iOS it doesnt show the image via url link but it makes the views for as many as the images are....
> if i make it as an UIImage i can see it normally.
> Maybe you should check it out!
> 
> P.S. when i upload from the parse dashboard from my Mac i can also see it normally.

Hey , I am taking about this pod , I raise the latest issue in this , please check , I need help
