### ISSUE TITLE
Space between images

### ISSUE THREAD

**Issue by traderdata** [zvonicek/ImageSlideshow#46]
Hi, ho can i remove the space that is shown between images?
Thanks

**Comment by zvonicek** [comment]
Hi! Currently there is no way to manually set the space between images. There's actually no space between them, but if you can see it, it's the impact of `contentScaleMode` set to `.ScaleAspectFit`, which is default. 

To remove the space, just set `contentScaleMode` to `.ScaleAspectFill` (but keep in mind that images will be fitted inside).
