### ISSUE TITLE
Download button?

### ISSUE THREAD

**Issue by kwstasna** [zvonicek/ImageSlideshow#50]
Hello.
I wanted your help to make a download button so the user can download the image if he likes it!
What is the file that handle the full screen view of the image?

**Comment by kafejo** [comment]
Take a look at the `ImageSlideshow` class.

**Comment by kwstasna** [comment]
I've managed to make an icon "save" at the `FullScreenSlideshowViewController.swift` But now i have to get the image which is displayed. Any idea of how to do it?

**Comment by kwstasna** [comment]
https://github.com/zvonicek/ImageSlideshow/pull/51
