### ISSUE TITLE
how can I load from Cache

### ISSUE THREAD

**Issue by jassimkm** [zvonicek/ImageSlideshow#52]
Hi is there any way to load from cache .

**Comment by kwstasna** [comment]
SDWebImage is not working at all. Are you sure that you have merge it? I also updated the pod but it doesn't recognize it,.

> Use of unresolved identifier 'SDWebImageSource'

Any idea?

**Comment by zvonicek** [comment]
@jassimkm I'm not sure what you mean. If you're using external sources such as AlamofireImage, they should do caching automatically for you.

@kwstasna This is probably not related to caching, but anyway – version with `SDWebImageSource` was not released yet. But I have just released a new version 0.5.1 which should have this.
