### ISSUE TITLE
Improve Examples

### ISSUE THREAD

**Issue by Ameer-Fares** [zvonicek/ImageSlideshow#57]
this is one of the greatest libraries ever, yet it was bit tricky to do actual dynamic work with it due to lack of prober example that support what to do, so when i figured out what to do I though you could add it to the examples :

var imageSource : [AlamofireSource] = [AlamofireSource]()
        for item in selectedDevice.deviceImages {
            imageSource.append(AlamofireSource(urlString: item.stringByAddingPercentEncodingWithAllowedCharacters( NSCharacterSet.URLQueryAllowedCharacterSet())!)!)
        }

this might not be the most advanced code ever, but it may be useful for many cases... hopefully you add this to the examples.

best regards.

**Comment by zvonicek** [comment]
Hi! I'm definitely planning to improve examples. Not sure if your case fits there, but will think about it.
