### ISSUE TITLE
Rotating Issue

### ISSUE THREAD

**Issue by htarwara6245** [zvonicek/ImageSlideshow#6]
First of all,Perfect library u got same as Apple PhotoScroller at WWDC.Thanks for your hard work.Really thanks.But,as u see,I got rotating issue from your library.Any help?

I cant wait to see your feature version and support for Swift 2

![test_2](https://cloud.githubusercontent.com/assets/10526402/10215126/0a1aebce-6845-11e5-99fe-c0b5daf8b845.gif)

**Comment by zvonicek** [comment]
Hi, thank you for your interest. I fixed this issue, check that out and let me know if the problem persists.

**Comment by htarwara6245** [comment]
Thank you...Really thank you from my heart...There will be many others who is stucking with the scrollview.I will try to help them with your library if u don't mind.Many newbie stuck at image scrolling with paging and zooming feature.And you really help me out.So do the others.Thanks.

[One Suggestion] ->You add tappedtoZoom feature when we see full screen.How about adding "Zoom to the specific point that we double tapped the image specific point we tapped".Thanks.
