### ISSUE TITLE
Swift 3 Support 

### ISSUE THREAD

**Issue by nevinjethmalani** [zvonicek/ImageSlideshow#61]
I am getting an error even when using AFnetworking with swift 3 in the file below. Let me know if I am doing something wrong. But it looks like this file has not been updated for 8 months which means it is not using the latest syntax. Can you also provide a timeline on when you will support alamofire? Love the pod! It is a very important part of our app. 

https://github.com/zvonicek/ImageSlideshow/blob/master/Pod/Classes/InputSources/AFURLSource.swift

**Comment by zvonicek** [comment]
Hi Nevin, I got back to you via email, but post respond to this issue so other users can see this as well. Code optimized for Swift 3 is available in `swift-3` experimental branch, I'd like to get back to it later this week and make it work with AFNetworking and Alamofire. However, my plan is to keep Swift 2.3 compatible version in master branch for a while, probably until v1.0 is released.

**Comment by zvonicek** [comment]
I fixed the [`swift-3` branch](https://github.com/zvonicek/ImageSlideshow/tree/swift-3) so it should now work correctly.
