### ISSUE TITLE
[Feature Request]Tapped to zoom at specific point

### ISSUE THREAD

**Issue by thihaaung6245** [zvonicek/ImageSlideshow#7]
[One Feature Request] ->You add tappedtoZoom feature when we see full screen.How about adding Zoom to the specific point that we double tapped the image specific point? Thanks.So, it will be more perfect.

**Comment by zvonicek** [comment]
Thanks for the feature request, this sounds really useful. Will investigate this.

**Comment by zvonicek** [comment]
This feature is out of the scope for now, so I'm closing the issue.
