### ISSUE TITLE
Disable dragging on  y-axis

### ISSUE THREAD

**Issue by zanesc** [zvonicek/ImageSlideshow#71]
It would be nice to be able to disable dragging on the y-axis. Only x-axis is needed. If I drag the image down it doesn't reset to the correct position. It resets properly if I drag the image up.

I am able to achieve my desired result by setting this property on the ViewController that holds the ImageSlideshow:

`automaticallyAdjustsScrollViewInsets = false`

**Comment by bendash** [comment]
thanks for sharing! i had this issue too and setting
`automaticallyAdjustsScrollViewInsets = false`
did the trick.

**Comment by zvonicek** [comment]
Thanks for your report. The problem was really caused by `automaticallyAdjustsScrollViewInsets`. I fixed the problem so it should work correctly even when this is set to true.
