### ISSUE TITLE
There are multiple dependencies with different sources for `ImageSlideshow` in `Podfile`

### ISSUE THREAD

**Issue by adinertia** [zvonicek/ImageSlideshow#73]
I have specified in my pod:
pod 'ImageSlideshow', :git => "https://github.com/zvonicek/ImageSlideshow.git", :branch => 'swift-3'
pod 'ImageSlideshow/Alamofire'

I'm getting error:
[!] There are multiple dependencies with different sources for `ImageSlideshow` in `Podfile`:

- ImageSlideshow (from `https://github.com/zvonicek/ImageSlideshow.git`, branch `swift-3`)
- ImageSlideshow/Alamofire

Any solution ?

**Comment by feiin** [comment]
only need like this

```
pod 'ImageSlideshow/Alamofire', :git => "https://github.com/zvonicek/ImageSlideshow.git", :branch => 'swift-3'
```

**Comment by adinertia** [comment]
Thanks it's working.
