### ISSUE TITLE
Opening FullscreenSlideshowViewController before setting and ImageSources crash

### ISSUE THREAD

**Issue by adamfraser** [zvonicek/ImageSlideshow#74]
If you try and open an FullscreenSlideshowViewController before setting any image sources on the slideshow the ZoomAnimatedTransitioning class crashes at line 137 as there is no currentSlideshow item.

**Comment by zvonicek** [comment]
Hi! Thanks for reporting this, I fixed this problem so it should now not crash on that anymore.
