### ISSUE TITLE
Must I use pod "ImageSlideshow/Kingfisher" even if I already have Kingfisher

### ISSUE THREAD

**Issue by kiwo12345** [zvonicek/ImageSlideshow#78]
Must I use pod "ImageSlideshow/Kingfisher" even if I already have Kingfisher installed, or can I simply use pod 'ImageSlideshow', '~> 0.6' ?

**Comment by feiin** [comment]
Yes,you should use pod "ImageSlideshow/Kingfisher",It won't install again Kingfisher if you already have Kingfisher installed.

**Comment by kiwo12345** [comment]
@feiin @zvonicek What do you mean it wont install it again if I already have Kingfisher. Whats the point of using pod ImageSlideshow/Kingfisher then?

**Comment by zvonicek** [comment]
`ImageSlideshow/Kingfisher` makes sure you have Kingfisher installed. If you already have it in your podfile, it'll simply use it, if not, it'll install it. 

`ImageSlideshow` pod is useful when you don't need any 3rd party networking library or you want to create your own InputSource.

**Comment by kiwo12345** [comment]
Thanks @zvonicek

**Comment by zvonicek** [comment]
But just remember to use it even if you have Kingfisher in your Podfile. The point is that it'll also include InputSource for Kingfisher.

**Comment by kiwo12345** [comment]
@zvonicek Sorry I forgot to ask you, does the `ImageSlideshow/Kingfisher` have a swift3 branch?

**Comment by zvonicek** [comment]
Sure, you can use
`pod 'ImageSlideshow/Kingfisher', :git => 'https://github.com/zvonicek/ImageSlideshow.git', :branch => 'swift-3'`

**Comment by kiwo12345** [comment]
Sorry I dont understand. Why should I use that pod if I already have
Kingfisher installed? - If it wont install it again

måndag 24 oktober 2016 skrev feiin <notifications@github.com>:

**Comment by zvonicek** [comment]
Read again my previous response to which you gave 👍 
😉

**Comment by kiwo12345** [comment]
@zvonicek No idea why that comment popped up now. I sent it through gmail a few days ago :O
