### ISSUE TITLE
Getting error "Use of undeclared type 'ImageSlideshow'"

### ISSUE THREAD

**Issue by surbhivarma90** [zvonicek/ImageSlideshow#79]
i have installed the pods for ImageSlideShow, and when i am trying to use it i am getting this error message. "Use of undeclared type 'ImageSlideshow"

Please help!

**Comment by zvonicek** [comment]
This seems to a problem of CocoaPods or your project configuration. Make sure you call `import ImageSlideshow` in the file you're using it.
