### ISSUE TITLE
[Feature Request] Image Caching Library Support

### ISSUE THREAD

**Issue by htarwara6245** [zvonicek/ImageSlideshow#8]
There are two image library that i currently used now which work perfect in Swift.How about adding support for that instead of Using AFNetworking (Obj-C Library).

https://github.com/Haneke/HanekeSwift
https://github.com/onevcat/Kingfisher

Thanks,Really love and interested to learn your hard work,I will try to pull request at your library with some extra feature when I can use completely github feature.

**Comment by zvonicek** [comment]
Yeah, I'm definitely open for supporting for more image loading and caching libraries. Haneke or Kingfisher would fit there really well, the support for some of those will definitely come. 
The reason there's just AFNetworking support so far is that I needed that for one of my projects :-)
