### ISSUE TITLE
Importing "Kingfisher"

### ISSUE THREAD

**Issue by mobilestar0223** [zvonicek/ImageSlideshow#81]
I want to use `KingfisherSource` and I don't know how to import this library using `Carthage`.
Please help me!
Thanks.

**Comment by zvonicek** [comment]
Hi! As far as I know, Carthage (unlike CocoaPods) currently does not support subspecs so it's not that simple to provide separate InputSources for different libraries. The best I can currently recommend is to install `ImageSlideshow` via Carthage and add `KingfisherSource` to your code manually.
