### ISSUE TITLE
Pod install Swift 3 not working

### ISSUE THREAD

**Issue by fernandocani** [zvonicek/ImageSlideshow#82]
Hi,

Tried to use the line `pod 'ImageSlideshow', '~> 1.0.0-beta.1'` and the response that i get is:

`pod install
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `ImageSlideshow (~> 1.0.0-beta.1)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `ImageSlideshow (~> 1.0.0-beta.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.`

![screen shot 2016-10-31 at 10 41 45 am](https://cloud.githubusercontent.com/assets/13990282/19854773/f1c26020-9f57-11e6-96a7-48bf659fd824.png)

**Comment by kafejo** [comment]
Have you tried `pod repo update` as the error message says?

**Comment by fernandocani** [comment]
Yes.

I managed to work by typing `pod 'ImageSlideshow', :branch => 'swift-3-dev'`.
The pod logs says that it installed the version 0.6

It's working, but i don't know how much right is this 'solution'.

**Comment by zvonicek** [comment]
Hi @fernandocani, as @kafejo pointed out, please try either `pod repo update` or directly `pod update`. Both of these commands (unlike `pod install`) update your local spec repo.

Your approach is not good for the future as it's not versioned, `swift-3-dev` branch may change or may even be deleted (which I actually plan to do). So I would recommend to stick with versioned CocoaPods releases.
