### ISSUE TITLE
ImageSlideshow in Swift 2.2

### ISSUE THREAD

**Issue by manulete19** [zvonicek/ImageSlideshow#84]
Hello, I would like to use your framework (version 0.6) in a project made in Swift 2.2 but when I try to compile the program, it gives me a bunch of errors. It seems like there are a syntaxis errors. Could you help me, please?

Thanks in advance!!

**Comment by zvonicek** [comment]
Hi, I tested it now on Xcode 7 / Swift 2.2 using `pod 'ImageSlideshow', '~> 0.6'` and it compiled correctly. Please check you're declaring this in Podfile correctly. Also make sure you have the latest CocoaPods version installed.
