### ISSUE TITLE
i'm trying to add image slideshow pod with my project and keep gave me this error 

### ISSUE THREAD

**Issue by ahmadsallam** [zvonicek/ImageSlideshow#86]
![screen shot 2016-11-09 at 2 54 59 pm](https://cloud.githubusercontent.com/assets/10084705/20139202/9f89089e-a68d-11e6-8193-b6597186448a.png)

i don't know what to do 
i'm using swift 3 
i add all files 
can any one help me how to do it with swift 3

**Comment by zvonicek** [comment]
`setImageInputs` requires array of sources but you're providing a single source. Just wrap it into an array.

**Comment by ahmadsallam** [comment]
ok i will try
can you just give me example please
thank you
