### ISSUE TITLE
is there a way to scroll two sperate slider together with one swipe?

### ISSUE THREAD

**Issue by theduman** [zvonicek/ImageSlideshow#89]
Hello guys.i have 2 slider in one controller,is there a way that when i swipe first slider make the second slider swipe too?

**Comment by zvonicek** [comment]
You need to do this manually, use `currentPageChanged` closure to be notified about a page change and update the second slider accordingly. If you, however, want synchronisation of animations, it gets more difficult and more changes in ImageSlideshow (especially in UIScrollViewDelegate part) would be needed.
