### ISSUE TITLE
[Request]It will be perfect photo async library if we add this feature

### ISSUE THREAD

**Issue by htarwara6245** [zvonicek/ImageSlideshow#9]
Mind please take a look at this,
https://www.dropbox.com/s/15o2s4y7sg0tmfw/LimPicker.zip?dl=0
This library is not perfect because it contain many error.Also I have to comment setSelected() and many things.That was the imagepicker used at WeChat.Please take a look and you will see what it need
So,how about you add these feature to your library for a perfect image library or create a new one.I am newbie,I also want to try my best.But,I need professional help too.

So,here is what i suggest
1.Add Support for action (like camera,gallery)
2.Can pick multiple images
3.There will be two view which was showing whole image screen and the other was thumbnail which we can delete and add new.
4.Adding full screen of  view of yours when we tapped 1st view image instead of thumbnail.

Here is the states that i was talking about
https://www.dropbox.com/s/jxkwa4zm4e1e1br/Multiple%20CollectionView.gif?dl=0

I think I requested too much.But if u do have anytime,please take a look and see what u can do to help me.Thanks.

**Comment by zvonicek** [comment]
The idea is to keep the library as simple as possible. This is beyond the core functionality I want to provide so there are no plans to implement such behaviour now.
