### ISSUE TITLE
Extra slide when dismissing FullScreenController

### ISSUE THREAD

**Issue by vongrad** [zvonicek/ImageSlideshow#91]
Hi,

I started using the ImageSlideshow today and it works great except one issue. When I open the FullScreenController, slide to different image than the initial one and then dismiss the FullScreenController, I end up with an extra gray slide without any image. I am using Alamofire as input source.

I also attached a small gif describing this issue

![slideshow_bug](https://cloud.githubusercontent.com/assets/3223913/20457704/13a82470-ae91-11e6-8eba-1aa952fd8f4a.gif)

I really hope somebody could have a look at it.

Thank you in advance!

**Comment by zvonicek** [comment]
Hi @vongrad, I think this issue is related to PR #92. I've just merged it to master so please try it if it helps. Otherwise let me know and I'll reopen this issue.
