### ISSUE TITLE
Feature Request: Customising the position of page control

### ISSUE THREAD

**Issue by TusharGarg** [zvonicek/ImageSlideshow#93]
Hello, 

Firstly, thanks for this library. 
In my current use case, I need to display the page control on the right side inside the scroll view.  With the current supported orientations of
```
insideScrollView
underScrollView
custom(padding: CGFloat)
```
only the `y` position of the page control can be manipulated. What do you think about allowing to manipulate the `x` position as well? (something like a right or left padding).

I will be happy to submit a pull request for it.

**Comment by zvonicek** [comment]
Hi, I was investigation this case and the best solution would be to completely rethink how page control position is set, which would, however, be a breaking change for other users. It would therefore be best to wait for this till v2.0 where I could do those changes. In the meanwhile you can change `pageControl` frame manually from your app and adjust it to the position you need.

**Comment by TusharGarg** [comment]
Ok. Thank you.

Regards
Tushar

~ trying to adapt fingers to mobile keyboard.

**Comment by zvonicek** [comment]
I've finally implemented more page indicator positioning flexibility in #251! Now you can easily adjust the `x` position using `PageIndicatorPosition(horizontal: .left, vertical: .under)`.
