### ISSUE TITLE
ImageSlideshow/Kingfisher in 2.3

### ISSUE THREAD

**Issue by SebastienGracia** [zvonicek/ImageSlideshow#94]
hello

i use 2.3 branch for a project

i want to install ImageSlideshow/Kingfisher

and when i pod install i have this error 

i use :   pod 'ImageSlideshow/Kingfisher'

> [!] There are only pre-release versions available satisfying the following requirements:
> 
> 	'ImageSlideshow/Kingfisher', '>= 0'
> 
> You should explicitly specify the version in order to install a pre-release version
> 

any idea to solve this ?

**Comment by zvonicek** [comment]
Just do what CocoaPods say – explicitly specify the version you want to use. In your case it's version 0.6, or you can directly specify the swift-2.3 branch instead.
