### ISSUE TITLE
Missing presentFullScreenController swift 2.3 version 0.6

### ISSUE THREAD

**Issue by Yozine** [zvonicek/ImageSlideshow#95]
The presentFullScreenController functionality is missing from version 0.6 for swift 2.3?
This feature appears to be missing as an endpoint from the Core/ImageSlideShowController and thus cannot be used.

**Comment by zvonicek** [comment]
Hi, yes, this feature was added later only to Swift 3 version, new features are not being integrated to Swift 2.3 version anymore. Since Swift 2.3 will not be supported in upcoming Xcode 8.2, I recommend you to transition your code to Swift 3.
